# Generated by Django 6.0 on 2025-12-26 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ontologies", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                (
                    "department",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=1024, null=True, unique=True
                    ),
                ),
                ("code", models.CharField(max_length=12, unique=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "department"),
                        name="unique_institution_name_department",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PrincipalInvestigator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("surname", models.CharField(max_length=512)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=22, null=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.institution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Project name.", max_length=512, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Project code.", max_length=6, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Project description.",
                        max_length=2048,
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="Project status (active / inactive)."
                    ),
                ),
                ("start_date", models.DateField(help_text="Project start date.")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Project end date.", null=True
                    ),
                ),
                (
                    "principal_investigator",
                    models.ForeignKey(
                        help_text="Project principal investigator (PI).",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.principalinvestigator",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(editable=False, unique=True)),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="FHIR Patient.active — whether this patient's record is in active use.",
                    ),
                ),
                ("name", models.CharField(help_text="Participant name")),
                ("surname", models.CharField(help_text="Participant surname")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Participant email address (Optional).",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone_number_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Participant phone number prefix (Optional). E.g +48",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "phone_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Participant phone number (Optional). E.g. 123456789",
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "male"),
                            ("female", "female"),
                            ("other", "other"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        help_text="Participant gender — male | female | other | unknown.",
                        max_length=7,
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="Participant birth date.", null=True
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="FHIR Patient.address[*] (Address list).",
                        null=True,
                    ),
                ),
                (
                    "deceased",
                    models.BooleanField(blank=True, help_text="Deceased?", null=True),
                ),
                (
                    "deceased_date_time",
                    models.DateTimeField(
                        blank=True, help_text="Deceased date.", null=True
                    ),
                ),
                (
                    "communication",
                    models.ForeignKey(
                        blank=True,
                        help_text="Preferred communication language.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ontologies.communicationlanguage",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this participant is associated with.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.institution",
                    ),
                ),
                (
                    "marital_status",
                    models.ForeignKey(
                        blank=True,
                        help_text="Participant marital status.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ontologies.maritalstatus",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Select the project this participant belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
                "ordering": ["pk", "project"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Provide document (unique) name.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Provide document description.", null=True
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Document creation date."
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="Upload file.",
                        null=True,
                        upload_to="documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "xlsx", "csv", "html"]
                            )
                        ],
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Select the project this document belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project's Document",
                "verbose_name_plural": "Project's Documents",
            },
        ),
    ]
