# Generated by Django 6.0 on 2025-12-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ICD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "healthy",
                    models.BooleanField(
                        default=False,
                        help_text="If true, patient is healthy and ICD code must be empty.",
                    ),
                ),
                (
                    "icd",
                    models.CharField(
                        blank=True,
                        help_text="ICD diagnosis code (required if not healthy).",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "icd_version",
                    models.CharField(
                        blank=True,
                        choices=[("ICD-10", "ICD-10"), ("ICD-11", "ICD-11")],
                        help_text="ICD classification version.",
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="participant",
            name="address",
        ),
        migrations.AddField(
            model_name="participant",
            name="apartment",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="city",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="country",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="street_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="deceased",
            field=models.BooleanField(default=False, help_text="Deceased?"),
        ),
        migrations.AddField(
            model_name="participant",
            name="icd",
            field=models.ManyToManyField(to="projects.icd"),
        ),
    ]
