# Generated by Django 6.0 on 2025-12-20 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="code",
            field=models.CharField(
                help_text="Project code.", max_length=6, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Project description.",
                max_length=2048,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, help_text="Project end date", null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                help_text="Project name.", max_length=512, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="principal_investigator",
            field=models.ForeignKey(
                help_text="Project principal investigator.",
                on_delete=django.db.models.deletion.PROTECT,
                to="projects.principalinvestigator",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(help_text="Project start date"),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.BooleanField(
                default=True, help_text="Project status (active / inactive)"
            ),
        ),
    ]
