# Generated by Django 6.0 on 2025-12-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinstitution",
            name="department",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="department",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="historicalinstitution",
            name="code",
            field=models.CharField(db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="historicalinstitution",
            name="name",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="institution",
            name="code",
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(max_length=1024),
        ),
    ]
