# Generated by Django 6.0 on 2026-01-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associatedfile",
            name="category",
            field=models.CharField(
                choices=[("Documents", "Documents"), ("Protocols", "Protocols")],
                default="Documents",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalassociatedfile",
            name="category",
            field=models.CharField(
                choices=[("Documents", "Documents"), ("Protocols", "Protocols")],
                default="Documents",
                max_length=20,
            ),
        ),
    ]
