# Generated by Django 6.0 on 2025-12-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="FHIR Patient.address[*] (Address list).",
                null=True,
            ),
        ),
    ]
