# Generated by Django 6.0 on 2025-12-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_code_alter_project_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Project description.",
                max_length=2048,
            ),
        ),
    ]
