# Generated by Django 6.0 on 2026-01-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_associatedfile_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["start_date"],
                "permissions": [
                    ("view_project_obj", "Can view project"),
                    ("change_project_obj", "Can change project"),
                    ("delete_project_obj", "Can delete project"),
                ],
            },
        ),
    ]
