# Generated by Django 6.0 on 2025-12-28 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontologies", "0001_initial"),
        (
            "projects",
            "0002_icd_remove_participant_address_participant_apartment_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="FHIR Patient.active — whether this participant record is in active use.",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="apartment",
            field=models.CharField(
                blank=True,
                help_text="Apartment/unit (optional).",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="birth_date",
            field=models.DateField(
                blank=True, help_text="Date of birth (optional).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="city",
            field=models.CharField(
                blank=True, help_text="City (optional).", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="communication",
            field=models.ForeignKey(
                blank=True,
                help_text="Preferred communication language (optional).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ontologies.communicationlanguage",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Country (optional). Example: Poland",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="deceased",
            field=models.BooleanField(
                default=False,
                help_text="FHIR Patient.deceasedBoolean — whether the participant is deceased.",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="deceased_date_time",
            field=models.DateTimeField(
                blank=True,
                help_text="FHIR Patient.deceasedDateTime — when the participant died (optional).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email address (optional).",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "male"),
                    ("female", "female"),
                    ("other", "other"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                help_text="FHIR Patient.gender — male | female | other | unknown.",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="icd",
            field=models.ManyToManyField(
                blank=True,
                help_text="ICD classifications for this participant (optional).",
                to="projects.icd",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="identifier",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="System-generated participant identifier (read-only).",
                max_length=128,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Institution this participant is associated with (required to generate identifier).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.institution",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="marital_status",
            field=models.ForeignKey(
                blank=True,
                help_text="Marital status (optional).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ontologies.maritalstatus",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="name",
            field=models.CharField(help_text="Given name.", max_length=255),
        ),
        migrations.AlterField(
            model_name="participant",
            name="phone_number",
            field=models.IntegerField(
                blank=True,
                help_text="Phone number (optional). Example: 123456789",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="phone_number_prefix",
            field=models.CharField(
                blank=True,
                help_text="Phone prefix (optional). Example: +48",
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="postal_code",
            field=models.CharField(
                blank=True,
                help_text="Postal/ZIP code (optional).",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="project",
            field=models.ForeignKey(
                help_text="Project this participant belongs to.",
                on_delete=django.db.models.deletion.PROTECT,
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="street",
            field=models.CharField(
                blank=True,
                help_text="Street name (optional).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="street_number",
            field=models.CharField(
                blank=True,
                help_text="Building number (optional).",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="surname",
            field=models.CharField(help_text="Family name / surname.", max_length=255),
        ),
    ]
