# Generated by Django 6.0 on 2025-12-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_historicalinstitution_department_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="institution",
            constraint=models.UniqueConstraint(
                fields=("name", "department"), name="unique_institution_name_department"
            ),
        ),
    ]
