# Generated by Django 6.0 on 2025-12-20 13:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="Project end date.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="principal_investigator",
            field=models.ForeignKey(
                help_text="Project principal investigator (PI).",
                on_delete=django.db.models.deletion.PROTECT,
                to="projects.principalinvestigator",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(help_text="Project start date."),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.BooleanField(
                default=True, help_text="Project status (active / inactive)."
            ),
        ),
        migrations.CreateModel(
            name="ProjectDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "xlsx", "csv"]
                            )
                        ],
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
