# Generated by Django 6.0 on 2025-12-28 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0003_alter_participant_active_alter_participant_apartment_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("biological_parent", "Biological parent"),
                            ("biological_child", "Biological child"),
                            ("mother", "Mother"),
                            ("father", "Father"),
                            ("son", "Son"),
                            ("daughter", "Daughter"),
                            ("full_sibling", "Full sibling (same parents)"),
                            ("half_sibling", "Half sibling (one parent)"),
                            ("twin_monozygotic", "Identical twin (monozygotic)"),
                            ("twin_dizygotic", "Fraternal twin (dizygotic)"),
                            ("grandparent", "Grandparent"),
                            ("grandchild", "Grandchild"),
                            ("aunt", "Aunt"),
                            ("uncle", "Uncle"),
                            ("niece", "Niece"),
                            ("nephew", "Nephew"),
                            ("cousin_first", "First cousin"),
                            ("cousin_second", "Second cousin"),
                            ("adoptive_parent", "Adoptive parent"),
                            ("adopted_child", "Adopted child"),
                            ("step_parent", "Step parent"),
                            ("step_child", "Step child"),
                            ("step_sibling", "Step sibling"),
                            ("guardian", "Legal guardian"),
                            ("spouse", "Spouse"),
                            ("partner", "Partner"),
                            ("ex_spouse", "Ex-spouse"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        help_text="Type of biological / legal relationship.",
                        max_length=32,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Optional free-text note (e.g. uncertain, reported by patient).",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_participant",
                    models.ForeignKey(
                        help_text="Source participant (relation direction start).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_from",
                        to="projects.participant",
                    ),
                ),
                (
                    "to_participant",
                    models.ForeignKey(
                        help_text="Target participant (relation direction end).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_to",
                        to="projects.participant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant relation",
                "verbose_name_plural": "Participant relations",
            },
        ),
        migrations.AddField(
            model_name="participant",
            name="relations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Biological, legal or social relations to other participants.",
                related_name="related_to",
                through="projects.ParticipantRelation",
                to="projects.participant",
            ),
        ),
        migrations.AddConstraint(
            model_name="participantrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_participant", models.F("to_participant")), _negated=True
                ),
                name="no_self_relation",
            ),
        ),
        migrations.AddConstraint(
            model_name="participantrelation",
            constraint=models.UniqueConstraint(
                fields=("from_participant", "to_participant", "relation_type"),
                name="unique_relation_per_type",
            ),
        ),
    ]
