# Generated by Django 6.0 on 2025-12-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_participantrelation_participant_relations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="deceased_date_time",
            field=models.DateField(
                blank=True,
                help_text="Deceased date — when the participant died (optional).",
                null=True,
            ),
        ),
    ]
