# Generated by Django 6.0 on 2025-12-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_project_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdocuments",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectdocuments",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
