# Generated by Django 6.0 on 2026-01-06 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_projectmembership_created_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectmembership",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="projectmembership",
            name="project",
        ),
        migrations.RemoveField(
            model_name="projectmembership",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["start_date"]},
        ),
        migrations.DeleteModel(
            name="HistoricalProjectMembership",
        ),
        migrations.DeleteModel(
            name="ProjectMembership",
        ),
    ]
