# Generated by Django 6.0 on 2025-12-20 14:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_projectdocuments_description_projectdocuments_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdocuments",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
