# Generated by Django 6.0 on 2025-12-28 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontologies", "0003_remove_diagnosis_uniq_diagnosis_system_code_and_more"),
        ("projects", "0005_alter_participant_deceased_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="healthy",
            field=models.BooleanField(
                default=True,
                help_text="Indicator if patients is/was healthy at the time of recruitment.",
            ),
        ),
        migrations.AlterField(
            model_name="participantrelation",
            name="relation_type",
            field=models.ForeignKey(
                help_text="Type of biological / legal relationship.",
                on_delete=django.db.models.deletion.PROTECT,
                to="ontologies.relationtype",
            ),
        ),
    ]
