# Generated by Django 6.0 on 2026-01-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_projectmembership_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associatedfile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="associatedfile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="historicalassociatedfile",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassociatedfile",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalinstitution",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalinstitution",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalparticipant",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalparticipant",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalparticipantrelation",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalparticipantrelation",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalprincipalinvestigator",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalprincipalinvestigator",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="participantrelation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="participantrelation",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="principalinvestigator",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="principalinvestigator",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
    ]
