# Generated by Django 6.0 on 2025-12-20 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_projectdocuments_uploaded_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectdocuments",
            options={
                "verbose_name": "Project's Document",
                "verbose_name_plural": "Project's Documents",
            },
        ),
        migrations.AlterField(
            model_name="projectdocuments",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "xlsx", "csv", "html"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="projectdocuments",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
