# Generated by Django 6.0 on 2025-12-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontologies", "0004_alter_icddiagnosis_options"),
        ("projects", "0006_participant_healthy_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ICD",
        ),
        migrations.AlterField(
            model_name="participant",
            name="icd",
            field=models.ManyToManyField(
                blank=True,
                help_text="ICD classifications for this participant (optional).",
                to="ontologies.icddiagnosis",
            ),
        ),
    ]
