# Generated by Django 6.0 on 2025-12-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_projectdocuments_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="fhire",
        ),
        migrations.AddField(
            model_name="participant",
            name="fhire_object",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
