# Generated by Django 6.0 on 2025-12-29 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_delete_icd_alter_participant_icd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this participant is associated with (required to generate identifier).",
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.institution",
            ),
        ),
    ]
