# Generated by Django 6.0 on 2025-12-29 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_alter_participant_institution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="healthy",
        ),
    ]
