# Generated by Django 6.0 on 2025-12-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_remove_participant_fhire_participant_fhire_object"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participant",
            old_name="fhire_object",
            new_name="fhir_object",
        ),
    ]
