# Generated by Django 6.0 on 2025-12-30 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_remove_participant_healthy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="institution",
            options={
                "verbose_name": "Institution",
                "verbose_name_plural": "Institutions",
            },
        ),
        migrations.AlterModelOptions(
            name="principalinvestigator",
            options={
                "verbose_name": "Principal Investigator",
                "verbose_name_plural": "Principal Investigators",
            },
        ),
        migrations.AlterField(
            model_name="institution",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Official postal address of the institution (must be unique if provided).",
                max_length=1024,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="code",
            field=models.CharField(
                help_text="Short unique institutional code used internally or in integrations.",
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="department",
            field=models.CharField(
                blank=True,
                help_text="Optional department, faculty, or unit within the institution.",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(
                help_text="Official name of the institution (e.g. university, hospital, research center).",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="principalinvestigator",
            name="email",
            field=models.EmailField(
                help_text="Primary contact email address of the principal investigator.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="principalinvestigator",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution the principal investigator is affiliated with.",
                on_delete=django.db.models.deletion.PROTECT,
                to="projects.institution",
            ),
        ),
        migrations.AlterField(
            model_name="principalinvestigator",
            name="name",
            field=models.CharField(
                help_text="First name of the principal investigator.", max_length=512
            ),
        ),
        migrations.AlterField(
            model_name="principalinvestigator",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Optional contact phone number (international format recommended).",
                max_length=22,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="principalinvestigator",
            name="surname",
            field=models.CharField(
                help_text="Last name of the principal investigator.", max_length=512
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="code",
            field=models.CharField(
                help_text="Project code.", max_length=8, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="projectdocuments",
            name="name",
            field=models.CharField(
                default="ZYZ",
                help_text="Provide document (unique) name.",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="principalinvestigator",
            constraint=models.UniqueConstraint(
                fields=("name", "surname"), name="unique_PI"
            ),
        ),
    ]
