# Generated by Django 6.0 on 2025-12-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_rename_fhire_object_participant_fhir_object"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="id",
        ),
        migrations.AlterField(
            model_name="participant",
            name="identifier",
            field=models.CharField(
                editable=False,
                help_text="Local identifier for participant.",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
