# Generated by Django 6.0 on 2025-12-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_alter_institution_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="participantrelation",
            name="unique_relation_per_type",
        ),
    ]
