# Generated by Django 6.0 on 2025-12-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_remove_participant_id_alter_participant_identifier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={
                "ordering": ["pk", "project"],
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
            },
        ),
        migrations.RemoveField(
            model_name="participant",
            name="identifier",
        ),
        migrations.AddField(
            model_name="participant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
