# Generated by Django 6.0 on 2025-12-30 21:08

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_remove_participantrelation_unique_relation_per_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="consent_file",
            field=models.FileField(
                blank=True,
                help_text="Signed consent document (PDF).",
                null=True,
                upload_to="consents/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="consent_signed_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when consent was signed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="consent_status",
            field=models.CharField(
                choices=[
                    ("given", "Given"),
                    ("withdrawn", "Withdrawn"),
                    ("pending", "Pending"),
                    ("expired", "Expired"),
                ],
                default="pending",
                help_text="Current legal consent status.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="consent_version",
            field=models.CharField(
                blank=True,
                help_text="Consent document version or identifier.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Object creation timestamp.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participant",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="gender",
            field=models.CharField(
                choices=[("male", "male"), ("female", "female")],
                help_text="Gender — male | female.",
                max_length=7,
            ),
        ),
    ]
