# Generated by Django 6.0 on 2025-12-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ontologies",
            "0007_remove_samplepreparation_uniq_samplepreparation_system_code_and_more",
        ),
        ("projects", "0013_alter_participant_icd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="icd",
            field=models.ManyToManyField(
                blank=True,
                help_text="ICD11 classifications for this participant (optional).",
                to="ontologies.icddiagnosis",
                verbose_name="ICD11",
            ),
        ),
    ]
