# Generated by Django 6.0 on 2025-12-31 12:22

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0014_alter_participant_icd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="consent_file",
            field=models.FileField(
                blank=True,
                help_text="Signed consent document (PDF).",
                null=True,
                upload_to=projects.models.project_consent_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="projectdocuments",
            name="document",
            field=models.FileField(
                blank=True,
                help_text="Upload file (PDF, XLSX, CSV).",
                null=True,
                upload_to=projects.models.project_document_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "xlsx", "csv"]
                    )
                ],
            ),
        ),
    ]
