# Generated by Django 6.0 on 2025-12-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0015_alter_participant_consent_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="consent_signed_at",
            field=models.DateField(
                blank=True, help_text="Timestamp when consent was signed.", null=True
            ),
        ),
    ]
