# Generated by Django 6.0 on 2025-12-31 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0016_alter_participant_consent_signed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="consent_version",
        ),
    ]
