# Generated by Django 6.0 on 2026-01-01 13:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ontologies",
            "0007_remove_samplepreparation_uniq_samplepreparation_system_code_and_more",
        ),
        ("projects", "0017_remove_participant_consent_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Object creation timestamp.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="institution",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AddField(
            model_name="participantrelation",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AddField(
            model_name="principalinvestigator",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Object creation timestamp.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="principalinvestigator",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Object creation timestamp.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AddField(
            model_name="projectdocuments",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Object creation timestamp.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectdocuments",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.CreateModel(
            name="HistoricalInstitution",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official name of the institution (e.g. university, hospital, research center).",
                        max_length=1024,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Optional department, faculty, or unit within the institution.",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Official postal address of the institution (must be unique if provided).",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Short unique institutional code used internally or in integrations.",
                        max_length=12,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Institution",
                "verbose_name_plural": "historical Institutions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalParticipant",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="System-generated participant identifier (read-only).",
                        max_length=128,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="FHIR Patient.active — whether this participant record is in active use.",
                    ),
                ),
                ("name", models.CharField(help_text="Given name.", max_length=255)),
                (
                    "surname",
                    models.CharField(
                        help_text="Family name / surname.", max_length=255
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")],
                        help_text="Gender — male | female.",
                        max_length=7,
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="Date of birth (optional).", null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address (optional).",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone_number_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Phone prefix (optional). Example: +48",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "phone_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Phone number (optional). Example: 123456789",
                        null=True,
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        help_text="Street name (optional).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "street_number",
                    models.CharField(
                        blank=True,
                        help_text="Building number (optional).",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "apartment",
                    models.CharField(
                        blank=True,
                        help_text="Apartment/unit (optional).",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="City (optional).",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="Postal/ZIP code (optional).",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Country (optional). Example: Poland",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "deceased",
                    models.BooleanField(
                        default=False,
                        help_text="FHIR Patient.deceasedBoolean — whether the participant is deceased.",
                    ),
                ),
                (
                    "deceased_date_time",
                    models.DateField(
                        blank=True,
                        help_text="Deceased date — when the participant died (optional).",
                        null=True,
                    ),
                ),
                (
                    "consent_status",
                    models.CharField(
                        choices=[
                            ("given", "Given"),
                            ("withdrawn", "Withdrawn"),
                            ("pending", "Pending"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        help_text="Current legal consent status.",
                        max_length=16,
                    ),
                ),
                (
                    "consent_file",
                    models.TextField(
                        blank=True,
                        help_text="Signed consent document (PDF).",
                        max_length=100,
                        null=True,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "consent_signed_at",
                    models.DateField(
                        blank=True,
                        help_text="Timestamp when consent was signed.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "communication",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Preferred communication language (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ontologies.communicationlanguage",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Institution this participant is associated with (required to generate identifier).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.institution",
                    ),
                ),
                (
                    "marital_status",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Marital status (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ontologies.maritalstatus",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Project this participant belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Participant",
                "verbose_name_plural": "historical Participants",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalParticipantRelation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Optional free-text note (e.g. uncertain, reported by patient).",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "from_participant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Source participant (relation direction start).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.participant",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "relation_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Type of biological / legal relationship.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ontologies.relationtype",
                    ),
                ),
                (
                    "to_participant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Target participant (relation direction end).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.participant",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Participant relation",
                "verbose_name_plural": "historical Participant relations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPrincipalInvestigator",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="First name of the principal investigator.",
                        max_length=512,
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        help_text="Last name of the principal investigator.",
                        max_length=512,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary contact email address of the principal investigator.",
                        max_length=254,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Optional contact phone number (international format recommended).",
                        max_length=22,
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Institution the principal investigator is affiliated with.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Principal Investigator",
                "verbose_name_plural": "historical Principal Investigators",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProject",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Project name.", max_length=512
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, help_text="Project code.", max_length=8
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Project description.",
                        max_length=2048,
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="Project status (active / inactive)."
                    ),
                ),
                ("start_date", models.DateField(help_text="Project start date.")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Project end date.", null=True
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "principal_investigator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Project principal investigator (PI).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.principalinvestigator",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical project",
                "verbose_name_plural": "historical projects",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProjectDocuments",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Provide document (unique) name.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Provide document description.", null=True
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Document creation date."
                    ),
                ),
                (
                    "document",
                    models.TextField(
                        blank=True,
                        help_text="Upload file (PDF, XLSX, CSV).",
                        max_length=100,
                        null=True,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "xlsx", "csv"]
                            )
                        ],
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Select the project this document belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Project's Document",
                "verbose_name_plural": "historical Project's Documents",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
