# Generated by Django 6.0 on 2026-01-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0018_institution_created_at_institution_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalprojectdocuments",
            name="uploaded_at",
        ),
        migrations.RemoveField(
            model_name="projectdocuments",
            name="uploaded_at",
        ),
        migrations.AlterField(
            model_name="historicalparticipantrelation",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="participantrelation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Object creation timestamp."
            ),
        ),
    ]
