# Generated by Django 6.0 on 2026-01-02 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_remove_historicalprojectdocuments_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="project",
            field=models.ForeignKey(
                help_text="Project this participant belongs to.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participants",
                to="projects.project",
            ),
        ),
    ]
