# Generated by Django 6.0 on 2025-12-31 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectrole",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="projectrole",
            name="core_projec_user_id_d28765_idx",
        ),
        migrations.RemoveIndex(
            model_name="projectrole",
            name="core_projec_project_16834f_idx",
        ),
        migrations.DeleteModel(
            name="ProjectRole",
        ),
    ]
