# Generated by Django 6.0 on 2025-12-22 11:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ontologies", "0001_initial"),
        ("projects", "0002_alter_participant_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short, unique protocol name.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed protocol description or steps."
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Optional protocol document (PDF, DOCX, etc.).",
                        null=True,
                        upload_to="protocols/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing protocol",
                "verbose_name_plural": "Processing protocols",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique storage identifier or name (e.g. Freezer A1).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "conditions",
                    models.TextField(
                        blank=True,
                        help_text="Storage conditions (e.g. -80°C, LN2 vapor phase, humidity notes).",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable physical location description.",
                        max_length=512,
                    ),
                ),
                (
                    "sensors",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        editable=False,
                        help_text="Read-only sensor metadata (temperature, alarms, door state, etc.).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage",
                "verbose_name_plural": "Storages",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Specimen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        editable=False,
                        help_text="System-generated unique specimen identifier.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional free-text notes about the specimen.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp."
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Participant from whom the specimen was collected (if applicable).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specimens",
                        to="projects.participant",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project to which this specimen belongs.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specimens",
                        to="projects.project",
                    ),
                ),
                (
                    "protocols",
                    models.ForeignKey(
                        blank=True,
                        help_text="Processing protocol applied to this specimen.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specimens",
                        to="biobank.processingprotocol",
                    ),
                ),
                (
                    "sample_type",
                    models.ForeignKey(
                        help_text="Type of biological material.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specimens",
                        to="ontologies.sampletype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Specimen",
                "verbose_name_plural": "Specimens",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Box identifier within the storage (e.g. Box 01, Rack A / Box 3).",
                        max_length=255,
                    ),
                ),
                (
                    "rows",
                    models.PositiveIntegerField(
                        default=9,
                        help_text="Number of rows in the box grid.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "cols",
                    models.PositiveIntegerField(
                        default=9,
                        help_text="Number of columns in the box grid.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        help_text="Storage unit where this box is located.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boxes",
                        to="biobank.storage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Box",
                "verbose_name_plural": "Boxes",
                "ordering": ["storage__name", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Aliquot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="System-generated unique aliquot identifier.",
                        max_length=96,
                        unique=True,
                    ),
                ),
                (
                    "row",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Row position in the box (1-based).",
                        null=True,
                    ),
                ),
                (
                    "col",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Column position in the box (1-based).",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp."
                    ),
                ),
                (
                    "box",
                    models.ForeignKey(
                        blank=True,
                        help_text="Box where this aliquot is stored.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aliquots",
                        to="biobank.box",
                    ),
                ),
                (
                    "specimen",
                    models.ForeignKey(
                        help_text="Parent specimen.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliquots",
                        to="biobank.specimen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aliquot",
                "verbose_name_plural": "Aliquots",
                "ordering": ["-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("box", "row", "col"),
                        name="unique_aliquot_position_in_box",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="box",
            constraint=models.UniqueConstraint(
                fields=("storage", "name"), name="unique_box_name_per_storage"
            ),
        ),
    ]
