# Generated by Django 6.0 on 2025-12-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biobank", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aliquot",
            options={
                "ordering": ["aliquot_id"],
                "verbose_name": "Aliquot",
                "verbose_name_plural": "Aliquots",
            },
        ),
        migrations.AlterModelOptions(
            name="donor",
            options={
                "ordering": ["donor_id", "project"],
                "verbose_name": "Donor",
                "verbose_name_plural": "Donors",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalaliquot",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Aliquot",
                "verbose_name_plural": "historical Aliquots",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldonor",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Donor",
                "verbose_name_plural": "historical Donors",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsample",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Sample",
                "verbose_name_plural": "historical Samples",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalstorage",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Storage",
                "verbose_name_plural": "historical Storage",
            },
        ),
        migrations.AlterModelOptions(
            name="sample",
            options={
                "ordering": ["collection_date"],
                "verbose_name": "Sample",
                "verbose_name_plural": "Samples",
            },
        ),
        migrations.AlterModelOptions(
            name="storage",
            options={"verbose_name": "Storage", "verbose_name_plural": "Storage"},
        ),
    ]
