# Generated by Django 6.0 on 2026-01-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biobank", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aliquot",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="aliquot",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="box",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="box",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="historicalaliquot",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaliquot",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbox",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbox",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalprocessingprotocol",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalprocessingprotocol",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalspecimen",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalspecimen",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstorage",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstorage",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="processingprotocol",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="processingprotocol",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="storage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="storage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
    ]
