# Generated by Django 5.2.7 on 2025-10-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biobank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliquot',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='aliquot',
            name='quality_units',
        ),
    ]
