# Generated by Django 6.0 on 2025-12-26 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("biobank", "0001_initial"),
        ("ontologies", "__first__"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specimen",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                help_text="Participant from whom the specimen was collected (if applicable).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specimens",
                to="projects.participant",
            ),
        ),
        migrations.AddField(
            model_name="specimen",
            name="project",
            field=models.ForeignKey(
                help_text="Project to which this specimen belongs.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specimens",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="specimen",
            name="protocols",
            field=models.ForeignKey(
                blank=True,
                help_text="Processing protocol applied to this specimen.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specimens",
                to="biobank.processingprotocol",
            ),
        ),
        migrations.AddField(
            model_name="specimen",
            name="sample_type",
            field=models.ForeignKey(
                help_text="Type of biological material.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specimens",
                to="ontologies.sampletype",
            ),
        ),
        migrations.AddField(
            model_name="aliquot",
            name="specimen",
            field=models.ForeignKey(
                help_text="Parent specimen.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliquots",
                to="biobank.specimen",
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="storage",
            field=models.ForeignKey(
                help_text="Storage unit where this box is located.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boxes",
                to="biobank.storage",
            ),
        ),
        migrations.AddConstraint(
            model_name="aliquot",
            constraint=models.UniqueConstraint(
                fields=("box", "row", "col"), name="unique_aliquot_position_in_box"
            ),
        ),
        migrations.AddConstraint(
            model_name="box",
            constraint=models.UniqueConstraint(
                fields=("storage", "name"), name="unique_box_name_per_storage"
            ),
        ),
    ]
