# Generated by Django 6.0 on 2026-01-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biobank", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="aliquot",
            name="aliquot_box_grid_idx",
        ),
        migrations.RemoveIndex(
            model_name="aliquot",
            name="aliquot_specimen_idx",
        ),
    ]
