# Generated by Django 6.0 on 2026-01-08 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biobank", "0002_alter_aliquot_created_at_alter_aliquot_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aliquot",
            options={},
        ),
        migrations.AlterModelOptions(
            name="specimen",
            options={"ordering": ("created_at",)},
        ),
    ]
