# Generated by Django 6.0 on 2025-12-17 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biobank", "0002_alter_aliquot_options_alter_donor_options_and_more"),
        ("ontologies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aliquot",
            name="preparation_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ontologies.samplepreparation",
            ),
        ),
        migrations.AlterField(
            model_name="aliquot",
            name="volume_or_mass",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalaliquot",
            name="preparation_method",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ontologies.samplepreparation",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaliquot",
            name="volume_or_mass",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
