# Generated by Django 5.2.7 on 2025-10-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biobank', '0002_remove_aliquot_quality_remove_aliquot_quality_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_code',
            new_name='project_id',
        ),
    ]
