# Generated by Django 6.0 on 2025-12-31 13:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biobank", "0002_initial"),
        (
            "ontologies",
            "0007_remove_samplepreparation_uniq_samplepreparation_system_code_and_more",
        ),
        ("projects", "0017_remove_participant_consent_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aliquot",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="specimen",
            options={"ordering": ["-id"]},
        ),
        migrations.RemoveConstraint(
            model_name="aliquot",
            name="unique_aliquot_position_in_box",
        ),
        migrations.AddField(
            model_name="aliquot",
            name="sample_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Aliquot material type (defaults to specimen sample type).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aliquots",
                to="ontologies.sampletype",
            ),
        ),
        migrations.AlterField(
            model_name="aliquot",
            name="box",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aliquots",
                to="biobank.box",
            ),
        ),
        migrations.AlterField(
            model_name="aliquot",
            name="col",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Column position in the box (1-based).",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="aliquot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="aliquot",
            name="identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                editable=False,
                help_text="System-generated unique aliquot identifier.",
                max_length=96,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="aliquot",
            name="row",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Row position in the box (1-based).",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="aliquot",
            name="specimen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliquots",
                to="biobank.specimen",
            ),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="identifier",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="System-generated unique specimen identifier.",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specimens",
                to="projects.participant",
            ),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specimens",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="protocols",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specimens",
                to="biobank.processingprotocol",
            ),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="sample_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specimens",
                to="ontologies.sampletype",
            ),
        ),
        migrations.AddIndex(
            model_name="aliquot",
            index=models.Index(
                fields=["box", "row", "col"], name="aliquot_box_grid_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aliquot",
            index=models.Index(
                fields=["specimen", "created_at"], name="aliquot_specimen_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="aliquot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("box__isnull", True),
                        ("col__isnull", True),
                        ("row__isnull", True),
                    ),
                    models.Q(
                        ("box__isnull", False),
                        ("col__isnull", False),
                        ("row__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="aliquot_box_row_col_all_or_none",
            ),
        ),
    ]
