# Generated by Django 6.0 on 2025-12-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biobank", "0003_alter_aliquot_preparation_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="donor",
            name="surname",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldonor",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldonor",
            name="surname",
            field=models.CharField(blank=True, null=True),
        ),
    ]
