# Generated by Django 6.0 on 2025-12-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biobank", "0003_alter_aliquot_options_alter_specimen_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storage",
            name="conditions",
            field=models.CharField(
                blank=True,
                help_text="Storage conditions (e.g. -80°C, LN2 vapor phase, humidity notes).",
            ),
        ),
    ]
