# Generated by Django 6.0 on 2026-01-01 14:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biobank", "0004_alter_storage_conditions"),
        (
            "ontologies",
            "0007_remove_samplepreparation_uniq_samplepreparation_system_code_and_more",
        ),
        ("projects", "0018_institution_created_at_institution_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aliquot",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Object creation timestamp.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="box",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AddField(
            model_name="processingprotocol",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Object creation timestamp.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="processingprotocol",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AddField(
            model_name="specimen",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AddField(
            model_name="storage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Object creation timestamp.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="storage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.CreateModel(
            name="HistoricalAliquot",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        editable=False,
                        help_text="System-generated unique aliquot identifier.",
                        max_length=96,
                    ),
                ),
                (
                    "row",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Row position in the box (1-based).",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "col",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Column position in the box (1-based).",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "box",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biobank.box",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sample_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Aliquot material type (defaults to specimen sample type).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ontologies.sampletype",
                    ),
                ),
                (
                    "specimen",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biobank.specimen",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aliquot",
                "verbose_name_plural": "historical aliquots",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBox",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Box identifier within the storage (e.g. Box 01, Rack A / Box 3).",
                        max_length=255,
                    ),
                ),
                (
                    "rows",
                    models.PositiveIntegerField(
                        default=9,
                        help_text="Number of rows in the box grid.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "cols",
                    models.PositiveIntegerField(
                        default=9,
                        help_text="Number of columns in the box grid.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Storage unit where this box is located.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biobank.storage",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Box",
                "verbose_name_plural": "historical Boxes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProcessingProtocol",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Short, unique protocol name.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed protocol description or steps."
                    ),
                ),
                (
                    "file",
                    models.TextField(
                        blank=True,
                        help_text="Optional protocol document (PDF, DOCX, etc.).",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Processing protocol",
                "verbose_name_plural": "historical Processing protocols",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSpecimen",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        editable=False,
                        help_text="System-generated unique specimen identifier.",
                        max_length=64,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.participant",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
                (
                    "protocols",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biobank.processingprotocol",
                    ),
                ),
                (
                    "sample_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ontologies.sampletype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical specimen",
                "verbose_name_plural": "historical specimens",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalStorage",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique storage identifier or name (e.g. Freezer A1).",
                        max_length=255,
                    ),
                ),
                (
                    "conditions",
                    models.CharField(
                        blank=True,
                        help_text="Storage conditions (e.g. -80°C, LN2 vapor phase, humidity notes).",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable physical location description.",
                        max_length=512,
                    ),
                ),
                (
                    "sensors",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        editable=False,
                        help_text="Read-only sensor metadata (temperature, alarms, door state, etc.).",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Storage",
                "verbose_name_plural": "historical Storages",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
