# Generated by Django 6.0 on 2026-01-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biobank", "0005_aliquot_updated_at_box_created_at_box_updated_at_and_more"),
        (
            "ontologies",
            "0007_remove_samplepreparation_uniq_samplepreparation_system_code_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="aliquot",
            name="aliquot_specimen_created_idx",
        ),
        migrations.AlterField(
            model_name="aliquot",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="historicalaliquot",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="historicalspecimen",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AddIndex(
            model_name="aliquot",
            index=models.Index(fields=["specimen"], name="aliquot_specimen_idx"),
        ),
    ]
