# Generated by Django 6.0 on 2025-12-20 16:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import lims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("principal_investigator", models.CharField(max_length=255)),
                (
                    "order_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "items_xlsx",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=lims.models.order_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(["xlsx"])
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("GOODS", "Goods (delivery)"), ("SERVICE", "Service")],
                        default="GOODS",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "catalog_number",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_price_gross",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "estimated_total_gross",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=14
                    ),
                ),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_items",
                        to="lims.order",
                    ),
                ),
            ],
            options={
                "ordering": ["expiration_date"],
            },
        ),
    ]
