# Generated by Django 6.0 on 2025-12-21 19:12

import django.core.validators
import django.db.models.deletion
import lims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_internal_id",
                    models.CharField(
                        blank=True,
                        help_text="Order internal (unique) ID.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "person_responsible",
                    models.CharField(
                        help_text="Person responsible for this particular order.",
                        max_length=255,
                    ),
                ),
                (
                    "order_list",
                    models.FileField(
                        blank=True,
                        help_text="The excel list of items/services to order, upload to fill order automatically.",
                        null=True,
                        upload_to=lims.models.order_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(["xlsx"])
                        ],
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        help_text="Total price estimated for this particular order.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Order description.", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Order creation date"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the project this order belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Product name.", max_length=255)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("CHEMISTRY", "CHEMISTRY"),
                            ("PLASTICS", "PLASTICS"),
                            ("SERVICE", "SERVICE"),
                        ],
                        help_text="Product category, either PLASTICS, CHEMISTRY or SERVICE.",
                        max_length=10,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Product provider e.g. Illumina",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "catalog_number",
                    models.CharField(
                        blank=True,
                        help_text="Product catalog number.",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "unit_price_gross",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Product gross price.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        default=False,
                        help_text="Indicator whether the product has been delivered and is available.",
                    ),
                ),
                (
                    "lot",
                    models.CharField(
                        blank=True,
                        help_text="Product-specific (unique) LOT number.",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "expiration_waring_date",
                    models.IntegerField(
                        default=30,
                        help_text="Number of days (default 30) before the expiration date when a warning should be triggered.",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, help_text="Product's expiration date.", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Record creation date."
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Order ID.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_items",
                        to="lims.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock items",
                "verbose_name_plural": "Stock items",
                "ordering": ["expiration_date"],
            },
        ),
    ]
