# Generated by Django 6.0 on 2026-01-06 10:18

import django.core.validators
import django.db.models.deletion
import lims.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LNotebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last object update timestamp."
                    ),
                ),
                ("name", models.CharField(max_length=512, unique=True)),
                ("content", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Laboratory notebook",
                "verbose_name_plural": "Laboratory notebooks",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last object update timestamp."
                    ),
                ),
                ("name", models.CharField(max_length=24, unique=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("yellow", "Yellow"),
                            ("red", "Red"),
                        ],
                        default="blue",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="HistoricalLNotebook",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=512)),
                ("content", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Laboratory notebook",
                "verbose_name_plural": "historical Laboratory notebooks",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOrder",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                (
                    "order_internal_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Order internal (unique) ID.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "person_responsible",
                    models.CharField(
                        help_text="Person responsible for this particular order.",
                        max_length=255,
                    ),
                ),
                (
                    "order_list",
                    models.TextField(
                        blank=True,
                        help_text="The excel list of items/services to order, upload to fill order automatically.",
                        max_length=100,
                        null=True,
                        validators=[
                            django.core.validators.FileExtensionValidator(["xlsx"])
                        ],
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        help_text="Total price estimated for this particular order.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Order description.", null=True
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Select the project this order belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Order",
                "verbose_name_plural": "historical Orders",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTag",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=24)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("yellow", "Yellow"),
                            ("red", "Red"),
                        ],
                        default="blue",
                        max_length=10,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical tag",
                "verbose_name_plural": "historical tags",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDocument",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                ("name", models.CharField(blank=True, db_index=True, max_length=255)),
                (
                    "file",
                    models.TextField(
                        max_length=100,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "xls",
                                    "xlsx",
                                    "doc",
                                    "docx",
                                    "csv",
                                ]
                            )
                        ],
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notebook",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="lims.lnotebook",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical document",
                "verbose_name_plural": "historical documents",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last object update timestamp."
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, unique=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=lims.models.notebook_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "xls",
                                    "xlsx",
                                    "doc",
                                    "docx",
                                    "csv",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "notebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="lims.lnotebook",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last object update timestamp."
                    ),
                ),
                (
                    "order_internal_id",
                    models.CharField(
                        blank=True,
                        help_text="Order internal (unique) ID.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "person_responsible",
                    models.CharField(
                        help_text="Person responsible for this particular order.",
                        max_length=255,
                    ),
                ),
                (
                    "order_list",
                    models.FileField(
                        blank=True,
                        help_text="The excel list of items/services to order, upload to fill order automatically.",
                        null=True,
                        upload_to=lims.models.order_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(["xlsx"])
                        ],
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        help_text="Total price estimated for this particular order.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Order description.", null=True
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the project this order belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalStockItem",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                ("name", models.CharField(help_text="Product name.", max_length=255)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("CHEMISTRY", "CHEMISTRY"),
                            ("PLASTICS", "PLASTICS"),
                            ("SERVICE", "SERVICE"),
                        ],
                        help_text="Product category, either PLASTICS, CHEMISTRY or SERVICE.",
                        max_length=10,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Product provider e.g. Illumina",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "catalog_number",
                    models.CharField(
                        blank=True,
                        help_text="Product catalog number.",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "unit_price_gross",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Product gross price.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        default=False,
                        help_text="Indicator whether the product has been delivered and is available.",
                    ),
                ),
                (
                    "lot",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Product-specific (unique) LOT number.",
                        null=True,
                        verbose_name="LOT",
                    ),
                ),
                (
                    "expiration_waring_date",
                    models.IntegerField(
                        default=30,
                        help_text="Number of days (default 30) before the expiration date when a warning should be triggered.",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, help_text="Product's expiration date.", null=True
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Order ID.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="lims.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Stock items",
                "verbose_name_plural": "historical Stock items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last object update timestamp."
                    ),
                ),
                ("name", models.CharField(help_text="Product name.", max_length=255)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("CHEMISTRY", "CHEMISTRY"),
                            ("PLASTICS", "PLASTICS"),
                            ("SERVICE", "SERVICE"),
                        ],
                        help_text="Product category, either PLASTICS, CHEMISTRY or SERVICE.",
                        max_length=10,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Product provider e.g. Illumina",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "catalog_number",
                    models.CharField(
                        blank=True,
                        help_text="Product catalog number.",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "unit_price_gross",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Product gross price.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        default=False,
                        help_text="Indicator whether the product has been delivered and is available.",
                    ),
                ),
                (
                    "lot",
                    models.CharField(
                        blank=True,
                        help_text="Product-specific (unique) LOT number.",
                        null=True,
                        unique=True,
                        verbose_name="LOT",
                    ),
                ),
                (
                    "expiration_waring_date",
                    models.IntegerField(
                        default=30,
                        help_text="Number of days (default 30) before the expiration date when a warning should be triggered.",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, help_text="Product's expiration date.", null=True
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Order ID.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_items",
                        to="lims.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock items",
                "verbose_name_plural": "Stock items",
                "ordering": ["expiration_date"],
            },
        ),
        migrations.CreateModel(
            name="LNotebookTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last object update timestamp."
                    ),
                ),
                (
                    "notebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lims.lnotebook"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lims.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notebook tag",
                "verbose_name_plural": "Notebook tags",
                "unique_together": {("notebook", "tag")},
            },
        ),
        migrations.AddField(
            model_name="lnotebook",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="notebooks",
                through="lims.LNotebookTag",
                to="lims.tag",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalLNotebookTag",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notebook",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="lims.lnotebook",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="lims.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Notebook tag",
                "verbose_name_plural": "historical Notebook tags",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
