# Generated by Django 6.0 on 2025-12-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lims", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-order_date"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="stockitem",
            options={
                "ordering": ["expiration_date"],
                "verbose_name": "Stock items",
                "verbose_name_plural": "Stock items",
            },
        ),
        migrations.AddField(
            model_name="stockitem",
            name="available",
            field=models.BooleanField(default=False),
        ),
    ]
