# Generated by Django 6.0 on 2025-12-26 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lims", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the project this order belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="order",
            field=models.ForeignKey(
                help_text="Order ID.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_items",
                to="lims.order",
            ),
        ),
        migrations.AddField(
            model_name="lnotebooktag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lims.tag"
            ),
        ),
        migrations.AddField(
            model_name="lnotebook",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="notebooks",
                through="lims.LNotebookTag",
                to="lims.tag",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lnotebooktag",
            unique_together={("notebook", "tag")},
        ),
    ]
