# Generated by Django 6.0 on 2026-01-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lims", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstockitem",
            name="ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Product REF number.",
                null=True,
                verbose_name="REF",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="ref",
            field=models.CharField(
                blank=True,
                help_text="Product REF number.",
                null=True,
                unique=True,
                verbose_name="REF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstockitem",
            name="lot",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Product LOT number.",
                null=True,
                verbose_name="LOT",
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="lot",
            field=models.CharField(
                blank=True,
                help_text="Product LOT number.",
                null=True,
                unique=True,
                verbose_name="LOT",
            ),
        ),
    ]
