# Generated by Django 6.0 on 2026-01-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lims", "0002_historicalstockitem_ref_stockitem_ref_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocument",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocument",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicallnotebook",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicallnotebook",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicallnotebooktag",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicallnotebooktag",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstockitem",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstockitem",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltag",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltag",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="lnotebook",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="lnotebook",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="lnotebooktag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="lnotebooktag",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
    ]
