# Generated by Django 6.0 on 2025-12-23 20:17

import django.core.validators
import django.db.models.deletion
import lims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lims", "0002_tag_lnotebook"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lnotebook",
            name="tags",
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to=lims.models.notebook_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "xls", "xlsx", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="lims.lnotebook",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
