# Generated by Django 6.0 on 2025-12-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lims", "0002_alter_order_options_alter_stockitem_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="principal_investigator",
            new_name="person_responsible",
        ),
    ]
