# Generated by Django 6.0 on 2026-01-08 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lims", "0003_alter_document_created_at_alter_document_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ("created_at",)},
        ),
    ]
