# Generated by Django 6.0 on 2026-01-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lims", "0003_lnotebooktag_created_at_lnotebooktag_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstockitem",
            name="lot",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Product-specific (unique) LOT number.",
                null=True,
                verbose_name="LOT",
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="lot",
            field=models.CharField(
                blank=True,
                help_text="Product-specific (unique) LOT number.",
                null=True,
                unique=True,
                verbose_name="LOT",
            ),
        ),
    ]
