# Generated by Django 6.0 on 2025-12-23 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lims", "0003_remove_lnotebook_tags_document_delete_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=24, unique=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("yellow", "Yellow"),
                            ("red", "Red"),
                        ],
                        default="blue",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AlterModelOptions(
            name="lnotebook",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Laboratory notebook",
                "verbose_name_plural": "Laboratory notebooks",
            },
        ),
        migrations.CreateModel(
            name="LNotebookTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lims.lnotebook"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lims.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notebook tag",
                "verbose_name_plural": "Notebook tags",
                "unique_together": {("notebook", "tag")},
            },
        ),
        migrations.AddField(
            model_name="lnotebook",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="notebooks",
                through="lims.LNotebookTag",
                to="lims.tag",
            ),
        ),
    ]
