"""
Django settings for ebdms project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

from django.urls import reverse_lazy
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _

from import_export.formats.base_formats import XLSX, CSV
from dotenv import load_dotenv

# reads variables from a .env file and sets them in os.environ
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$qp5w)=7)$-sc0_^_m067aow*(!rsi-nt3fdc=z&)$!r4zi#ri"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "false").lower().strip() == "true"
MFA = os.getenv("MFA", "true").lower().strip() == "true"

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    # Unfold
    "unfold",
    "unfold.contrib.forms",
    "unfold.contrib.import_export",
    "unfold.contrib.simple_history",
    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.humanize",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.contenttypes",
    # OTP / MFA
    "django_otp",
    "django_otp.plugins.otp_totp",
    # installed
    "reversion",
    "crispy_forms",
    "import_export",
    "simple_history",
    "rest_framework",
    "django_minio_backend.apps.DjangoMinioBackendConfig",
    # apps
    "core",
    "ontologies",
    "projects",
    "lims",
    "biobank",
    "ehr",
    "ngs",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_otp.middleware.OTPMiddleware",
    "core.middleware.AdminOTPEnforceMiddleware",  # custom
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

AUTHENTICATION_BACKENDS = ("django.contrib.auth.backends.ModelBackend",)
ANONYMOUS_USER_NAME = None

ROOT_URLCONF = "ebdms.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "debug": True,
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Unfold global config (replacement for old DAISY_SETTINGS branding)
UNFOLD = {
    "SITE_TITLE": "EBDMS",
    "SITE_HEADER": "EBDMS Management",
    "SITE_URL": "/",
    "STYLES": [
        "/static/admin/reversion-unfold.css",
    ],
    "SITE_ICON": {
        "light": lambda request: static("logo/pum.png"),
        "dark": lambda request: static("logo/pum.png"),
    },
    "SITE_LOGO": {
        "light": lambda request: static("logo/pum.png"),
        "dark": lambda request: static("logo/pum.png"),
    },
    "SITE_SYMBOL": "biotech",
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/svg+xml",
            "href": lambda request: static("logo/pum.png"),
        },
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "SHOW_BACK_BUTTON": True,
    # Login
    "LOGIN": {
        "image": lambda request: static("logo/pum.png"),
    },
    # Light as default (forced)
    "THEME": "light",
    # Hook dashboard
    "DASHBOARD_CALLBACK": "ebdms.views.dashboard_callback",
    # Site dropdown
    "SITE_DROPDOWN": [
        {
            "icon": "diamond",
            "title": _("RCMC"),
            "link": "https://rcmc.pum.edu.pl/",
            "attrs": {
                "target": "_blank",
            },
        },
    ],
    # Sidebar with icons
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Management"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                    {
                        "title": "MFA devices",
                        "icon": "security",
                        "link": reverse_lazy("admin:otp_totp_totpdevice_changelist"),
                    },
                ],
            },
            {
                "title": _("Projects"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Institutions"),
                        "icon": "domain",
                        "link": reverse_lazy("admin:projects_institution_changelist"),
                    },
                    {
                        "title": _("Principal Investigators (PI)"),
                        "icon": "group",
                        "link": reverse_lazy(
                            "admin:projects_principalinvestigator_changelist"
                        ),
                    },
                    {
                        "title": _("Projects"),
                        "icon": "rocket",
                        "link": reverse_lazy("admin:projects_project_changelist"),
                    },
                    {
                        "title": _("Participants"),
                        "icon": "people",
                        "link": reverse_lazy("admin:projects_participant_changelist"),
                    },
                ],
            },
            {
                "title": _("Laboratory Information System (LIMS)"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Orders"),
                        "icon": "warehouse",
                        "link": reverse_lazy("admin:lims_order_changelist"),
                    },
                    {
                        "title": _("Stock"),
                        "icon": "labs",
                        "link": reverse_lazy("admin:lims_stockitem_changelist"),
                    },
                    {
                        "title": _("Laboratory notebooks"),
                        "icon": "computer",
                        "link": reverse_lazy("admin:lims_lnotebook_changelist"),
                    },
                ],
            },
            {
                "title": _("Biobank"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Storage"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:biobank_storage_changelist"),
                    },
                    {
                        "title": _("Specimens"),
                        "icon": "science",
                        "link": reverse_lazy("admin:biobank_specimen_changelist"),
                    },
                    {
                        "title": _("Aliquots"),
                        "icon": "vaccines",
                        "link": reverse_lazy("admin:biobank_aliquot_changelist"),
                    },
                    {
                        "title": _("Processing protocols"),
                        "icon": "description",
                        "link": reverse_lazy(
                            "admin:biobank_processingprotocol_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _("Electronic Health Record (EHR)"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Forms"),
                        "icon": "people",
                        "link": reverse_lazy("admin:ehr_form_changelist"),
                    },
                    {
                        "title": _("Assignments"),
                        "icon": "attachment",
                        "link": reverse_lazy("admin:ehr_assignment_changelist"),
                    },
                    {
                        "title": _("Responses"),
                        "icon": "people",
                        "link": reverse_lazy("admin:ehr_response_changelist"),
                    },
                ],
            },
            {
                "title": _("Omics"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Data"),
                        "icon": "description",
                        "link": reverse_lazy("admin:ngs_omicsartifact_changelist"),
                    },
                    {
                        "title": _("Devices"),
                        "icon": "memory",
                        "link": reverse_lazy("admin:ngs_device_changelist"),
                    },
                    {
                        "title": _("Targets"),
                        "icon": "target",
                        "link": reverse_lazy("admin:ngs_target_changelist"),
                    },
                    {
                        "title": _("Chemistry"),
                        "icon": "lab_profile",
                        "link": reverse_lazy("admin:ngs_chemistry_changelist"),
                    },
                ],
            },
        ],
    },
}

WSGI_APPLICATION = "ebdms.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "app_db"),
        "USER": os.environ.get("POSTGRES_USER", "app_user"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "app_pass"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    },
}

# DATABASE_ROUTERS = []

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
ADMIN_TWO_FACTOR_NAME = "RCMC-PUM-BIOBANK"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Berlin"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "/static/"

# For production: where collectstatic puts files
STATIC_ROOT = BASE_DIR / "staticfiles"

# For development: your own static assets
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Storages definition (from django 4.2), for static and media files
# Configured for Minio backend, but also configurable for AWS S3
MINIO_ENDPOINT_URL = os.environ["MINIO_ENDPOINT_URL"]
MINIO_PUBLIC_URL = os.environ["MINIO_PUBLIC_URL"]

MINIO_ACCESS_KEY = os.environ["MINIO_ROOT_USER"]
MINIO_SECRET_KEY = os.environ["MINIO_ROOT_PASSWORD"]

MINIO_REGION = os.environ["MINIO_REGION"]

MINIO_DEFAULT_BUCKET = os.environ["MINIO_DEFAULT_BUCKET"]
MINIO_STATIC_BUCKET = os.environ["MINIO_STATIC_BUCKET"]


def strip_scheme(url: str) -> str:
    return url.replace("http://", "").replace("https://", "").rstrip("/")


MINIO_ENDPOINT = strip_scheme(MINIO_ENDPOINT_URL)
MINIO_EXTERNAL_ENDPOINT = strip_scheme(MINIO_PUBLIC_URL)

STORAGES = {
    "staticfiles": {
        "BACKEND": "django_minio_backend.models.MinioBackendStatic",
        "OPTIONS": {
            "MINIO_ENDPOINT": MINIO_ENDPOINT,
            "MINIO_ACCESS_KEY": MINIO_ACCESS_KEY,
            "MINIO_SECRET_KEY": MINIO_SECRET_KEY,
            "MINIO_USE_HTTPS": not DEBUG,
            "MINIO_REGION": MINIO_REGION,
            "MINIO_URL_EXPIRY_HOURS": timedelta(days=1),
            "MINIO_CONSISTENCY_CHECK_ON_START": True,
            "MINIO_STATIC_FILES_BUCKET": MINIO_STATIC_BUCKET,
        },
    },
    "default": {
        "BACKEND": "django_minio_backend.models.MinioBackend",
        "OPTIONS": {
            "MINIO_ENDPOINT": MINIO_ENDPOINT,
            "MINIO_EXTERNAL_ENDPOINT": MINIO_EXTERNAL_ENDPOINT,
            "MINIO_EXTERNAL_ENDPOINT_USE_HTTPS": not DEBUG,
            "MINIO_ACCESS_KEY": MINIO_ACCESS_KEY,
            "MINIO_SECRET_KEY": MINIO_SECRET_KEY,
            "MINIO_USE_HTTPS": not DEBUG,
            "MINIO_REGION": MINIO_REGION,
            "MINIO_PRIVATE_BUCKETS": [MINIO_DEFAULT_BUCKET],
            "MINIO_PUBLIC_BUCKETS": [MINIO_STATIC_BUCKET],
            "MINIO_DEFAULT_BUCKET": MINIO_DEFAULT_BUCKET,
            "MINIO_STATIC_FILES_BUCKET": MINIO_STATIC_BUCKET,
            "MINIO_URL_EXPIRY_HOURS": timedelta(days=1),
            "MINIO_CONSISTENCY_CHECK_ON_START": False,
            "MINIO_POLICY_HOOKS": [],
            "MINIO_BUCKET_CHECK_ON_SAVE": False,
            # Multipart
            "MINIO_MULTIPART_UPLOAD": False,
            "MINIO_MULTIPART_THRESHOLD": 100 * 1024 * 1024,
            "MINIO_MULTIPART_PART_SIZE": 100 * 1024 * 1024,
            # URL caching
            "MINIO_URL_CACHING_ENABLED": True,
            "MINIO_URL_CACHE_TIMEOUT": 60 * 60 * 8,
            "MINIO_URL_CACHE_PREFIX": "minio_url_",
        },
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CRISPY
CRISPY_TEMPLATE_PACK = "unfold_crispy"
CRISPY_ALLOWED_TEMPLATE_PACKS = ["unfold_crispy"]

# IMPORT EXPORT
IMPORT_EXPORT_USE_TRANSACTIONS = True
IMPORT_EXPORT_SKIP_ADMIN_LOG = False
IMPORT_EXPORT_SKIP_ADMIN_CONFIRM = False

IMPORT_EXPORT_FORMATS = [XLSX, CSV]

# REST-API
# REST_FRAMEWORK = {
#     # Use Django's standard `django.contrib.auth` permissions,
#     # or allow read-only access for unauthenticated users.
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
#     ]
# }

# Simple history
# https://django-simple-history.readthedocs.io/en/stable/
SIMPLE_HISTORY_REVERT_DISABLED = False
SIMPLE_HISTORY_ENFORCE_HISTORY_MODEL_PERMISSIONS = True
