# Generated by Django 6.0 on 2026-01-06 10:18

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last object update timestamp."
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code — stable machine-readable code (within the system).",
                        max_length=64,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable preferred label.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
                (
                    "sop",
                    models.FileField(
                        blank=True,
                        help_text="Optional PDF SOP attached to this term.",
                        null=True,
                        upload_to="sops/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection method",
                "verbose_name_plural": "Collection methods",
                "ordering": ("name",),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "code"),
                        name="uniq_collectionmethod_system_code",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CommunicationLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last object update timestamp."
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code — stable machine-readable code (within the system).",
                        max_length=64,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable preferred label.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Communication language",
                "verbose_name_plural": "Communication languages",
                "ordering": ("name",),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "code"),
                        name="uniq_communicationlanguage_system_code",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCollectionMethod",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code — stable machine-readable code (within the system).",
                        max_length=64,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable preferred label.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
                (
                    "sop",
                    models.TextField(
                        blank=True,
                        help_text="Optional PDF SOP attached to this term.",
                        max_length=100,
                        null=True,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Collection method",
                "verbose_name_plural": "historical Collection methods",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCommunicationLanguage",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code — stable machine-readable code (within the system).",
                        max_length=64,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable preferred label.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Communication language",
                "verbose_name_plural": "historical Communication languages",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalICDDiagnosis",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code — stable machine-readable code (within the system).",
                        max_length=64,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable preferred label.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        choices=[("icd11", "ICD-11")],
                        help_text="Which ICD revision this code belongs to.",
                        max_length=8,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ICD diagnosis",
                "verbose_name_plural": "historical ICD diagnoses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMaritalStatus",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code — stable machine-readable code (within the system).",
                        max_length=64,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable preferred label.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Marital status",
                "verbose_name_plural": "historical Marital statuses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRelationType",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code — stable machine-readable code (within the system).",
                        max_length=64,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable preferred label.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Relation type",
                "verbose_name_plural": "historical Relation types",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSampleType",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code — stable machine-readable code (within the system).",
                        max_length=64,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable preferred label.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Sample type",
                "verbose_name_plural": "historical Sample types",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalUnit",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code — stable machine-readable code (within the system).",
                        max_length=64,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable preferred label.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Unit",
                "verbose_name_plural": "historical Units",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ICDDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last object update timestamp."
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code — stable machine-readable code (within the system).",
                        max_length=64,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable preferred label.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        choices=[("icd11", "ICD-11")],
                        help_text="Which ICD revision this code belongs to.",
                        max_length=8,
                    ),
                ),
            ],
            options={
                "verbose_name": "ICD diagnosis",
                "verbose_name_plural": "ICD diagnoses",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("version", "system", "code"),
                        name="uniq_icd_version_system_code",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MaritalStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last object update timestamp."
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code — stable machine-readable code (within the system).",
                        max_length=64,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable preferred label.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marital status",
                "verbose_name_plural": "Marital statuses",
                "ordering": ("name",),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "code"), name="uniq_maritalstatus_system_code"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RelationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last object update timestamp."
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code — stable machine-readable code (within the system).",
                        max_length=64,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable preferred label.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relation type",
                "verbose_name_plural": "Relation types",
                "ordering": ("name",),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "code"), name="uniq_relationtype_system_code"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SampleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last object update timestamp."
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code — stable machine-readable code (within the system).",
                        max_length=64,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable preferred label.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sample type",
                "verbose_name_plural": "Sample types",
                "ordering": ("name",),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "code"), name="uniq_sampletype_system_code"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last object update timestamp."
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code — stable machine-readable code (within the system).",
                        max_length=64,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable preferred label.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
                "ordering": ("name",),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "code"), name="uniq_unit_system_code"
                    )
                ],
            },
        ),
    ]
