# Generated by Django 6.0 on 2025-12-26 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommunicationLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="FHIR Coding.system — URI identifying the terminology system (e.g. SNOMED, LOINC, or internal namespace).",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="FHIR Coding.code — stable machine-readable code.",
                        max_length=64,
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        help_text="FHIR Coding.display — human-readable term.",
                        max_length=255,
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True,
                        help_text="FHIR CodeableConcept.text — free text representation.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Communication language",
                "verbose_name_plural": "Communication languages",
            },
        ),
        migrations.CreateModel(
            name="MaritalStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="FHIR Coding.system — URI identifying the terminology system (e.g. SNOMED, LOINC, or internal namespace).",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="FHIR Coding.code — stable machine-readable code.",
                        max_length=64,
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        help_text="FHIR Coding.display — human-readable term.",
                        max_length=255,
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True,
                        help_text="FHIR CodeableConcept.text — free text representation.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marital status",
                "verbose_name_plural": "Marital statuses",
            },
        ),
        migrations.CreateModel(
            name="CollectionMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="FHIR Coding.system — URI identifying the terminology system (e.g. SNOMED, LOINC, or internal namespace).",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="FHIR Coding.code — stable machine-readable code.",
                        max_length=64,
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        help_text="FHIR Coding.display — human-readable term.",
                        max_length=255,
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True,
                        help_text="FHIR CodeableConcept.text — free text representation.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
                (
                    "sop",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="sops/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ("display",),
                "abstract": False,
                "unique_together": {("system", "code")},
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="FHIR Coding.system — URI identifying the terminology system (e.g. SNOMED, LOINC, or internal namespace).",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="FHIR Coding.code — stable machine-readable code.",
                        max_length=64,
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        help_text="FHIR Coding.display — human-readable term.",
                        max_length=255,
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True,
                        help_text="FHIR CodeableConcept.text — free text representation.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
            ],
            options={
                "ordering": ("display",),
                "abstract": False,
                "unique_together": {("system", "code")},
            },
        ),
        migrations.CreateModel(
            name="SamplePreparation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="FHIR Coding.system — URI identifying the terminology system (e.g. SNOMED, LOINC, or internal namespace).",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="FHIR Coding.code — stable machine-readable code.",
                        max_length=64,
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        help_text="FHIR Coding.display — human-readable term.",
                        max_length=255,
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True,
                        help_text="FHIR CodeableConcept.text — free text representation.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
                (
                    "sop",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="sops/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ("display",),
                "abstract": False,
                "unique_together": {("system", "code")},
            },
        ),
        migrations.CreateModel(
            name="SampleStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="FHIR Coding.system — URI identifying the terminology system (e.g. SNOMED, LOINC, or internal namespace).",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="FHIR Coding.code — stable machine-readable code.",
                        max_length=64,
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        help_text="FHIR Coding.display — human-readable term.",
                        max_length=255,
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True,
                        help_text="FHIR CodeableConcept.text — free text representation.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
                (
                    "sop",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="sops/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ("display",),
                "abstract": False,
                "unique_together": {("system", "code")},
            },
        ),
        migrations.CreateModel(
            name="SampleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="FHIR Coding.system — URI identifying the terminology system (e.g. SNOMED, LOINC, or internal namespace).",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="FHIR Coding.code — stable machine-readable code.",
                        max_length=64,
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        help_text="FHIR Coding.display — human-readable term.",
                        max_length=255,
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True,
                        help_text="FHIR CodeableConcept.text — free text representation.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
            ],
            options={
                "ordering": ("display",),
                "abstract": False,
                "unique_together": {("system", "code")},
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="FHIR Coding.system — URI identifying the terminology system (e.g. SNOMED, LOINC, or internal namespace).",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="FHIR Coding.code — stable machine-readable code.",
                        max_length=64,
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        help_text="FHIR Coding.display — human-readable term.",
                        max_length=255,
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True,
                        help_text="FHIR CodeableConcept.text — free text representation.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
            ],
            options={
                "ordering": ("display",),
                "abstract": False,
                "unique_together": {("system", "code")},
            },
        ),
    ]
