# Generated by Django 6.0 on 2025-12-28 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontologies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ICDDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code — stable machine-readable code (within the system).",
                        max_length=64,
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        help_text="Display — human-readable preferred label.",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name — optional free-text representation / synonym.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        choices=[("icd10", "ICD-10"), ("icd11", "ICD-11")],
                        help_text="Which ICD revision this code belongs to.",
                        max_length=8,
                    ),
                ),
            ],
            options={
                "verbose_name": "ICD diagnosis",
                "verbose_name_plural": "ICD diagnoses",
                "ordering": ("display",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RelationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code — stable machine-readable code (within the system).",
                        max_length=64,
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        help_text="Display — human-readable preferred label.",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name — optional free-text representation / synonym.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Local description / definition of the term.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relation type",
                "verbose_name_plural": "Relation types",
                "ordering": ("display",),
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="SampleStorage",
        ),
        migrations.AlterModelOptions(
            name="collectionmethod",
            options={
                "ordering": ("display",),
                "verbose_name": "Collection method",
                "verbose_name_plural": "Collection methods",
            },
        ),
        migrations.AlterModelOptions(
            name="communicationlanguage",
            options={
                "ordering": ("display",),
                "verbose_name": "Communication language",
                "verbose_name_plural": "Communication languages",
            },
        ),
        migrations.AlterModelOptions(
            name="diagnosis",
            options={
                "ordering": ("display",),
                "verbose_name": "Diagnosis",
                "verbose_name_plural": "Diagnoses",
            },
        ),
        migrations.AlterModelOptions(
            name="maritalstatus",
            options={
                "ordering": ("display",),
                "verbose_name": "Marital status",
                "verbose_name_plural": "Marital statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="samplepreparation",
            options={
                "ordering": ("display",),
                "verbose_name": "Sample preparation",
                "verbose_name_plural": "Sample preparations",
            },
        ),
        migrations.AlterModelOptions(
            name="sampletype",
            options={
                "ordering": ("display",),
                "verbose_name": "Sample type",
                "verbose_name_plural": "Sample types",
            },
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={
                "ordering": ("display",),
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
            },
        ),
        migrations.AlterUniqueTogether(
            name="collectionmethod",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="diagnosis",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="samplepreparation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="sampletype",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="unit",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="communicationlanguage",
            name="text",
        ),
        migrations.RemoveField(
            model_name="maritalstatus",
            name="text",
        ),
        migrations.AddField(
            model_name="collectionmethod",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name — optional free-text representation / synonym.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="communicationlanguage",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name — optional free-text representation / synonym.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name — optional free-text representation / synonym.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="maritalstatus",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name — optional free-text representation / synonym.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="samplepreparation",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name — optional free-text representation / synonym.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sampletype",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name — optional free-text representation / synonym.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name — optional free-text representation / synonym.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="collectionmethod",
            name="code",
            field=models.CharField(
                help_text="Code — stable machine-readable code (within the system).",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="collectionmethod",
            name="display",
            field=models.CharField(
                help_text="Display — human-readable preferred label.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="collectionmethod",
            name="sop",
            field=models.FileField(
                blank=True,
                help_text="Optional PDF SOP attached to this term.",
                null=True,
                upload_to="sops/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="collectionmethod",
            name="system",
            field=models.CharField(
                help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="communicationlanguage",
            name="code",
            field=models.CharField(
                help_text="Code — stable machine-readable code (within the system).",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="communicationlanguage",
            name="display",
            field=models.CharField(
                help_text="Display — human-readable preferred label.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="communicationlanguage",
            name="system",
            field=models.CharField(
                help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="code",
            field=models.CharField(
                help_text="Code — stable machine-readable code (within the system).",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="display",
            field=models.CharField(
                help_text="Display — human-readable preferred label.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="system",
            field=models.CharField(
                help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="maritalstatus",
            name="code",
            field=models.CharField(
                help_text="Code — stable machine-readable code (within the system).",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="maritalstatus",
            name="display",
            field=models.CharField(
                help_text="Display — human-readable preferred label.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="maritalstatus",
            name="system",
            field=models.CharField(
                help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="samplepreparation",
            name="code",
            field=models.CharField(
                help_text="Code — stable machine-readable code (within the system).",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="samplepreparation",
            name="display",
            field=models.CharField(
                help_text="Display — human-readable preferred label.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="samplepreparation",
            name="sop",
            field=models.FileField(
                blank=True,
                help_text="Optional PDF SOP attached to this term.",
                null=True,
                upload_to="sops/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="samplepreparation",
            name="system",
            field=models.CharField(
                help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sampletype",
            name="code",
            field=models.CharField(
                help_text="Code — stable machine-readable code (within the system).",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="sampletype",
            name="display",
            field=models.CharField(
                help_text="Display — human-readable preferred label.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="sampletype",
            name="system",
            field=models.CharField(
                help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="code",
            field=models.CharField(
                help_text="Code — stable machine-readable code (within the system).",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="display",
            field=models.CharField(
                help_text="Display — human-readable preferred label.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="system",
            field=models.CharField(
                help_text="System / namespace (e.g. 'http://terminology.hl7.org/CodeSystem/v3-MaritalStatus').",
                max_length=255,
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionmethod",
            constraint=models.UniqueConstraint(
                fields=("system", "code"), name="uniq_collectionmethod_system_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="communicationlanguage",
            constraint=models.UniqueConstraint(
                fields=("system", "code"), name="uniq_communicationlanguage_system_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="diagnosis",
            constraint=models.UniqueConstraint(
                fields=("system", "code"), name="uniq_diagnosis_system_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="maritalstatus",
            constraint=models.UniqueConstraint(
                fields=("system", "code"), name="uniq_maritalstatus_system_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="samplepreparation",
            constraint=models.UniqueConstraint(
                fields=("system", "code"), name="uniq_samplepreparation_system_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="sampletype",
            constraint=models.UniqueConstraint(
                fields=("system", "code"), name="uniq_sampletype_system_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                fields=("system", "code"), name="uniq_unit_system_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="icddiagnosis",
            constraint=models.UniqueConstraint(
                fields=("version", "system", "code"),
                name="uniq_icd_version_system_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="relationtype",
            constraint=models.UniqueConstraint(
                fields=("system", "code"), name="uniq_relationtype_system_code"
            ),
        ),
        migrations.RemoveField(
            model_name="collectionmethod",
            name="text",
        ),
        migrations.RemoveField(
            model_name="diagnosis",
            name="text",
        ),
        migrations.RemoveField(
            model_name="samplepreparation",
            name="text",
        ),
        migrations.RemoveField(
            model_name="sampletype",
            name="text",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="text",
        ),
    ]
