# Generated by Django 6.0 on 2025-12-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ontologies", "0002_icddiagnosis_relationtype_delete_samplestorage_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="diagnosis",
            name="uniq_diagnosis_system_code",
        ),
        migrations.DeleteModel(
            name="Diagnosis",
        ),
    ]
