# Generated by Django 6.0 on 2025-12-28 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ontologies", "0003_remove_diagnosis_uniq_diagnosis_system_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="icddiagnosis",
            options={
                "verbose_name": "ICD diagnosis",
                "verbose_name_plural": "ICD diagnoses",
            },
        ),
    ]
