# Generated by Django 6.0 on 2025-12-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontologies", "0004_alter_icddiagnosis_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="icddiagnosis",
            name="version",
            field=models.CharField(
                choices=[("icd11", "ICD-11")],
                help_text="Which ICD revision this code belongs to.",
                max_length=8,
            ),
        ),
    ]
