# Generated by Django 6.0 on 2025-12-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontologies", "0005_alter_icddiagnosis_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collectionmethod",
            options={
                "ordering": ("name",),
                "verbose_name": "Collection method",
                "verbose_name_plural": "Collection methods",
            },
        ),
        migrations.AlterModelOptions(
            name="communicationlanguage",
            options={
                "ordering": ("name",),
                "verbose_name": "Communication language",
                "verbose_name_plural": "Communication languages",
            },
        ),
        migrations.AlterModelOptions(
            name="maritalstatus",
            options={
                "ordering": ("name",),
                "verbose_name": "Marital status",
                "verbose_name_plural": "Marital statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="relationtype",
            options={
                "ordering": ("name",),
                "verbose_name": "Relation type",
                "verbose_name_plural": "Relation types",
            },
        ),
        migrations.AlterModelOptions(
            name="samplepreparation",
            options={
                "ordering": ("name",),
                "verbose_name": "Sample preparation",
                "verbose_name_plural": "Sample preparations",
            },
        ),
        migrations.AlterModelOptions(
            name="sampletype",
            options={
                "ordering": ("name",),
                "verbose_name": "Sample type",
                "verbose_name_plural": "Sample types",
            },
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={
                "ordering": ("name",),
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
            },
        ),
        migrations.RemoveField(
            model_name="collectionmethod",
            name="display",
        ),
        migrations.RemoveField(
            model_name="communicationlanguage",
            name="display",
        ),
        migrations.RemoveField(
            model_name="icddiagnosis",
            name="display",
        ),
        migrations.RemoveField(
            model_name="maritalstatus",
            name="display",
        ),
        migrations.RemoveField(
            model_name="relationtype",
            name="display",
        ),
        migrations.RemoveField(
            model_name="samplepreparation",
            name="display",
        ),
        migrations.RemoveField(
            model_name="sampletype",
            name="display",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="display",
        ),
        migrations.AlterField(
            model_name="collectionmethod",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Code — stable machine-readable code (within the system).",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="collectionmethod",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Human-readable preferred label.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="communicationlanguage",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Code — stable machine-readable code (within the system).",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="communicationlanguage",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Human-readable preferred label.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="icddiagnosis",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Code — stable machine-readable code (within the system).",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="icddiagnosis",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Human-readable preferred label.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="maritalstatus",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Code — stable machine-readable code (within the system).",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="maritalstatus",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Human-readable preferred label.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="relationtype",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Code — stable machine-readable code (within the system).",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="relationtype",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Human-readable preferred label.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="samplepreparation",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Code — stable machine-readable code (within the system).",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="samplepreparation",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Human-readable preferred label.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sampletype",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Code — stable machine-readable code (within the system).",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="sampletype",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Human-readable preferred label.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Code — stable machine-readable code (within the system).",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Human-readable preferred label.",
                max_length=255,
            ),
        ),
    ]
