# Generated by Django 6.0 on 2025-12-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ontologies", "0006_alter_collectionmethod_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="samplepreparation",
            name="uniq_samplepreparation_system_code",
        ),
        migrations.DeleteModel(
            name="SamplePreparation",
        ),
    ]
