# Generated by Django 6.0 on 2025-12-31 14:07

import django.db.models.deletion
import ngs.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("biobank", "0004_alter_storage_conditions"),
        ("projects", "0017_remove_participant_consent_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chemistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Chemistry",
                "verbose_name_plural": "Chemistries",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("vendor", models.CharField(blank=True, max_length=200)),
                ("model", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Target",
                "verbose_name_plural": "Targets",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="OmicsArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=ngs.models.data_path,
                    ),
                ),
                ("fastqc_metrics", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "md5",
                    models.CharField(
                        blank=True, db_index=True, editable=False, max_length=32
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "Specimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omics_artifacts",
                        to="biobank.specimen",
                    ),
                ),
                (
                    "aliquot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: specific aliquot used to generate this artifact.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omics_artifacts",
                        to="biobank.aliquot",
                    ),
                ),
                (
                    "chemistry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omics_artifacts",
                        to="ngs.chemistry",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omics_artifacts",
                        to="ngs.device",
                    ),
                ),
                (
                    "indexed_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="If this is a .tbi, point to the primary VCF/BCF this indexes.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="index_files",
                        to="ngs.omicsartifact",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omics_artifacts",
                        to="projects.project",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omics_artifacts",
                        to="ngs.target",
                    ),
                ),
            ],
            options={
                "verbose_name": "Omics artifact",
                "verbose_name_plural": "Omics artifacts",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["project", "Specimen"],
                        name="ngs_omicsar_project_b0608b_idx",
                    ),
                    models.Index(
                        fields=["Specimen", "target"],
                        name="ngs_omicsar_Specime_e97796_idx",
                    ),
                    models.Index(
                        fields=["device"], name="ngs_omicsar_device__2b8832_idx"
                    ),
                    models.Index(
                        fields=["chemistry"], name="ngs_omicsar_chemist_eca25a_idx"
                    ),
                    models.Index(fields=["md5"], name="ngs_omicsar_md5_b4eb48_idx"),
                ],
            },
        ),
    ]
