# Generated by Django 6.0 on 2026-01-06 10:46

import django.core.validators
import django.db.models.deletion
import ngs.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("biobank", "0001_initial"),
        ("projects", "0002_alter_associatedfile_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chemistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last object update timestamp."
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Chemistry",
                "verbose_name_plural": "Chemistries",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last object update timestamp."
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("vendor", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last object update timestamp."
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Target",
                "verbose_name_plural": "Targets",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="HistoricalChemistry",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Chemistry",
                "verbose_name_plural": "historical Chemistries",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDevice",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("vendor", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Device",
                "verbose_name_plural": "historical Devices",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTarget",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Target",
                "verbose_name_plural": "historical Targets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OmicsArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last object update timestamp."
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=ngs.models.data_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "vcf",
                                    "vcf.gz",
                                    "bcf",
                                    "bcf.gz",
                                    "parquet",
                                ],
                                message="Unsupported file type. Allowed: .vcf, .vcf.gz, .bcf, .parquet",
                            )
                        ],
                    ),
                ),
                (
                    "index",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=ngs.models.data_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["tbi"],
                                message="Unsupported file type. Allowed: .tbi",
                            )
                        ],
                    ),
                ),
                (
                    "qc_metrics",
                    models.FileField(
                        upload_to=ngs.models.qc_data_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["csv", "json"],
                                message="Unsupported file type. Allowed: .csv, .json",
                            )
                        ],
                        verbose_name="QC metrics",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, editable=False, null=True
                    ),
                ),
                (
                    "aliquot",
                    models.ForeignKey(
                        help_text="Optional: specific aliquot used to generate this artifact.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omics_artifacts",
                        to="biobank.aliquot",
                    ),
                ),
                (
                    "chemistry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omics_artifacts",
                        to="ngs.chemistry",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omics_artifacts",
                        to="ngs.device",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omics_artifacts",
                        to="projects.project",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omics_artifacts",
                        to="ngs.target",
                    ),
                ),
            ],
            options={
                "verbose_name": "Omics artifact",
                "verbose_name_plural": "Omics artifacts",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="HistoricalOmicsArtifact",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                (
                    "file",
                    models.TextField(
                        max_length=100,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "vcf",
                                    "vcf.gz",
                                    "bcf",
                                    "bcf.gz",
                                    "parquet",
                                ],
                                message="Unsupported file type. Allowed: .vcf, .vcf.gz, .bcf, .parquet",
                            )
                        ],
                    ),
                ),
                (
                    "index",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["tbi"],
                                message="Unsupported file type. Allowed: .tbi",
                            )
                        ],
                    ),
                ),
                (
                    "qc_metrics",
                    models.TextField(
                        max_length=100,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["csv", "json"],
                                message="Unsupported file type. Allowed: .csv, .json",
                            )
                        ],
                        verbose_name="QC metrics",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, editable=False, null=True
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "aliquot",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Optional: specific aliquot used to generate this artifact.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biobank.aliquot",
                    ),
                ),
                (
                    "chemistry",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ngs.chemistry",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ngs.device",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ngs.target",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Omics artifact",
                "verbose_name_plural": "historical Omics artifacts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
