# Generated by Django 6.0 on 2026-01-06 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biobank", "0001_initial"),
        ("ngs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalomicsartifact",
            name="aliquot",
        ),
        migrations.RemoveField(
            model_name="omicsartifact",
            name="aliquot",
        ),
        migrations.AddField(
            model_name="historicalomicsartifact",
            name="specimen",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Specific specimen / samples used to generate this artifact.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="biobank.specimen",
            ),
        ),
        migrations.AddField(
            model_name="omicsartifact",
            name="specimen",
            field=models.ForeignKey(
                default=1,
                help_text="Specific specimen / samples used to generate this artifact.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="omics_artifacts",
                to="biobank.specimen",
            ),
            preserve_default=False,
        ),
    ]
