# Generated by Django 6.0 on 2025-12-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ngs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={"verbose_name": "Device", "verbose_name_plural": "Devices"},
        ),
        migrations.AlterModelOptions(
            name="omicsfile",
            options={"verbose_name": "NGS", "verbose_name_plural": "NGS"},
        ),
    ]
