# Generated by Django 6.0 on 2026-01-02 13:02

import django.core.validators
import ngs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ngs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalomicsartifact",
            name="file",
            field=models.TextField(
                max_length=100,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "vcf",
                            "vcf.gz",
                            "bcf",
                            "bcf.gz",
                            "parquet",
                        ],
                        message="Unsupported file type. Allowed: .vcf, .vcf.gz, .bcf, .parquet",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalomicsartifact",
            name="index",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["tbi"],
                        message="Unsupported file type. Allowed: .tbi",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="omicsartifact",
            name="file",
            field=models.FileField(
                upload_to=ngs.models.data_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "vcf",
                            "vcf.gz",
                            "bcf",
                            "bcf.gz",
                            "parquet",
                        ],
                        message="Unsupported file type. Allowed: .vcf, .vcf.gz, .bcf, .parquet",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="omicsartifact",
            name="index",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=ngs.models.data_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["tbi"],
                        message="Unsupported file type. Allowed: .tbi",
                    )
                ],
            ),
        ),
    ]
