# Generated by Django 6.0 on 2026-01-06 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biobank", "0001_initial"),
        ("ngs", "0002_remove_historicalomicsartifact_aliquot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalomicsartifact",
            name="specimen",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Specific specimen / sample used to generate this artifact.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="biobank.specimen",
            ),
        ),
        migrations.AlterField(
            model_name="omicsartifact",
            name="specimen",
            field=models.ForeignKey(
                help_text="Specific specimen / sample used to generate this artifact.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="omics_artifacts",
                to="biobank.specimen",
            ),
        ),
    ]
