# Generated by Django 6.0 on 2026-01-01 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ngs", "0002_chemistry_created_at_chemistry_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="model",
        ),
        migrations.RemoveField(
            model_name="historicaldevice",
            name="model",
        ),
    ]
