# Generated by Django 6.0 on 2026-01-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ngs", "0003_remove_device_model_remove_historicaldevice_model"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="omicsartifact",
            name="ngs_omicsar_project_b0608b_idx",
        ),
        migrations.RemoveIndex(
            model_name="omicsartifact",
            name="ngs_omicsar_Specime_e97796_idx",
        ),
        migrations.RemoveIndex(
            model_name="omicsartifact",
            name="ngs_omicsar_device__2b8832_idx",
        ),
        migrations.RemoveIndex(
            model_name="omicsartifact",
            name="ngs_omicsar_chemist_eca25a_idx",
        ),
        migrations.RemoveIndex(
            model_name="omicsartifact",
            name="ngs_omicsar_md5_b4eb48_idx",
        ),
        migrations.RenameField(
            model_name="historicalomicsartifact",
            old_name="fastqc_metrics",
            new_name="qc_metrics",
        ),
        migrations.RenameField(
            model_name="omicsartifact",
            old_name="fastqc_metrics",
            new_name="qc_metrics",
        ),
        migrations.RemoveField(
            model_name="historicalomicsartifact",
            name="metadata",
        ),
        migrations.AlterField(
            model_name="omicsartifact",
            name="md5",
            field=models.CharField(
                blank=True, editable=False, max_length=32, unique=True
            ),
        ),
        migrations.RemoveField(
            model_name="omicsartifact",
            name="metadata",
        ),
    ]
