# Generated by Django 6.0 on 2026-01-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ngs", "0003_alter_historicalomicsartifact_specimen_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chemistry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="chemistry",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="historicalchemistry",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalchemistry",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevice",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevice",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalomicsartifact",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalomicsartifact",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltarget",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltarget",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="omicsartifact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="omicsartifact",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
    ]
