# Generated by Django 6.0 on 2026-01-01 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biobank", "0006_remove_aliquot_aliquot_specimen_created_idx_and_more"),
        ("ngs", "0004_remove_omicsartifact_ngs_omicsar_project_b0608b_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalomicsartifact",
            name="Specimen",
        ),
        migrations.RemoveField(
            model_name="omicsartifact",
            name="Specimen",
        ),
        migrations.AlterField(
            model_name="omicsartifact",
            name="aliquot",
            field=models.ForeignKey(
                help_text="Optional: specific aliquot used to generate this artifact.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="omics_artifacts",
                to="biobank.aliquot",
            ),
        ),
    ]
