# Generated by Django 6.0 on 2026-01-08 22:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ngs", "0004_alter_chemistry_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="omicsartifact",
            options={
                "verbose_name": "Omics artifact",
                "verbose_name_plural": "Omics artifacts",
            },
        ),
    ]
