# Generated by Django 6.0 on 2026-01-01 14:56

import django.core.validators
import ngs.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ngs", "0005_remove_historicalomicsartifact_specimen_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalomicsartifact",
            name="indexed_file",
        ),
        migrations.RemoveField(
            model_name="historicalomicsartifact",
            name="md5",
        ),
        migrations.RemoveField(
            model_name="omicsartifact",
            name="indexed_file",
        ),
        migrations.RemoveField(
            model_name="omicsartifact",
            name="md5",
        ),
        migrations.AddField(
            model_name="historicalomicsartifact",
            name="index",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "vcf",
                            "vcf.gz",
                            "bcf",
                            "bcf.gz",
                            "parquet",
                        ],
                        message="Unsupported file type. Allowed: .vcf, .vcf.gz, .bcf, .parquet",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="historicalomicsartifact",
            name="metadata",
            field=models.JSONField(blank=True, default={}, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="omicsartifact",
            name="index",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=ngs.models.data_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "vcf",
                            "vcf.gz",
                            "bcf",
                            "bcf.gz",
                            "parquet",
                        ],
                        message="Unsupported file type. Allowed: .vcf, .vcf.gz, .bcf, .parquet",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="omicsartifact",
            name="metadata",
            field=models.JSONField(blank=True, default={}, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="historicalomicsartifact",
            name="file",
            field=models.TextField(
                max_length=100,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["tbi"],
                        message="Unsupported file type. Allowed: .tbi",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalomicsartifact",
            name="qc_metrics",
            field=models.TextField(
                max_length=100,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv", "json"],
                        message="Unsupported file type. Allowed: .csv, .json",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="omicsartifact",
            name="file",
            field=models.FileField(
                upload_to=ngs.models.data_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["tbi"],
                        message="Unsupported file type. Allowed: .tbi",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="omicsartifact",
            name="qc_metrics",
            field=models.FileField(
                upload_to=ngs.models.qc_data_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv", "json"],
                        message="Unsupported file type. Allowed: .csv, .json",
                    )
                ],
            ),
        ),
    ]
