# Generated by Django 6.0 on 2026-01-08 22:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ngs", "0005_alter_omicsartifact_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Last object update timestamp.",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Repository",
                "verbose_name_plural": "Repositories",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="historicalomicsartifact",
            name="repository_id",
            field=models.CharField(
                blank=True, help_text="Record ID e.g. GSE number.", null=True
            ),
        ),
        migrations.AddField(
            model_name="omicsartifact",
            name="repository_id",
            field=models.CharField(
                blank=True, help_text="Record ID e.g. GSE number.", null=True
            ),
        ),
        migrations.CreateModel(
            name="HistoricalRepository",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="Object creation timestamp.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="Last object update timestamp.",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Repository",
                "verbose_name_plural": "historical Repositories",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="historicalomicsartifact",
            name="repository_name",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Data repository e.g. EGA, SRA, GEO.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ngs.repository",
            ),
        ),
        migrations.AddField(
            model_name="omicsartifact",
            name="repository_name",
            field=models.ForeignKey(
                blank=True,
                help_text="Data repository e.g. EGA, SRA, GEO.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ngs.repository",
            ),
        ),
    ]
