# Generated by Django 6.0 on 2026-01-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ngs", "0006_repository_historicalomicsartifact_repository_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrepository",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalomicsartifact",
            name="repository_id",
            field=models.CharField(
                blank=True,
                help_text="Record ID e.g. GSE number.",
                null=True,
                verbose_name="Repository ID",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrepository",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="omicsartifact",
            name="repository_id",
            field=models.CharField(
                blank=True,
                help_text="Record ID e.g. GSE number.",
                null=True,
                verbose_name="Repository ID",
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
