# Generated by Django 6.0 on 2026-01-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ngs", "0006_remove_historicalomicsartifact_indexed_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalomicsartifact",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="omicsartifact",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
    ]
