# Generated by Django 6.0 on 2026-01-01 15:57

import django.core.validators
import ngs.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ngs", "0007_alter_historicalomicsartifact_metadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalomicsartifact",
            name="qc_metrics",
            field=models.TextField(
                max_length=100,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv", "json"],
                        message="Unsupported file type. Allowed: .csv, .json",
                    )
                ],
                verbose_name="QC metrics",
            ),
        ),
        migrations.AlterField(
            model_name="omicsartifact",
            name="qc_metrics",
            field=models.FileField(
                upload_to=ngs.models.qc_data_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv", "json"],
                        message="Unsupported file type. Allowed: .csv, .json",
                    )
                ],
                verbose_name="QC metrics",
            ),
        ),
    ]
