# Generated by Django 5.2.7 on 2025-10-12 20:54

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biobank', '0003_rename_project_code_project_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EHRModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('schema', django_jsonform.models.fields.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'EHR Form',
                'verbose_name_plural': 'EHR Forms',
            },
        ),
        migrations.CreateModel(
            name='EHRRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.ehrmodel')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biobank.patient')),
            ],
            options={
                'verbose_name': 'EHR Record',
                'verbose_name_plural': 'EHR Records',
            },
        ),
    ]
