# Generated by Django 6.0 on 2025-12-18 10:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("biobank", "0003_alter_aliquot_preparation_method_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, null=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalForm",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, null=True)),
                ("slug", models.SlugField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical form",
                "verbose_name_plural": "historical forms",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFormField",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("key", models.SlugField(max_length=100)),
                ("label", models.CharField(max_length=255)),
                ("help_text", models.TextField(blank=True, default="")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean"),
                            ("email", "Email"),
                            ("url", "URL"),
                            ("date", "Date"),
                            ("datetime", "Datetime"),
                            ("choice", "Choice"),
                            ("multichoice", "Multi-choice"),
                            ("file", "File"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("choices", models.JSONField(blank=True, null=True)),
                ("use_min_length", models.BooleanField(default=False)),
                ("min_length", models.PositiveIntegerField(blank=True, null=True)),
                ("use_max_length", models.BooleanField(default=False)),
                ("max_length", models.PositiveIntegerField(blank=True, null=True)),
                ("use_min_value", models.BooleanField(default=False)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                ("use_max_value", models.BooleanField(default=False)),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                ("use_regex", models.BooleanField(default=False)),
                (
                    "regex_pattern",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "regex_message",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("regex_flags", models.PositiveIntegerField(default=0)),
                ("use_email_validator", models.BooleanField(default=False)),
                ("use_url_validator", models.BooleanField(default=False)),
                ("use_slug_validator", models.BooleanField(default=False)),
                ("use_unicode_slug_validator", models.BooleanField(default=False)),
                ("use_file_extension_validator", models.BooleanField(default=False)),
                ("allowed_extensions", models.JSONField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ehr.form",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical form field",
                "verbose_name_plural": "historical form fields",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalResponse",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("result", models.JSONField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biobank.donor",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ehr.form",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical response",
                "verbose_name_plural": "historical responses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("result", models.JSONField()),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="biobank.donor"
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="ehr.form"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("key", models.SlugField(max_length=100)),
                ("label", models.CharField(max_length=255)),
                ("help_text", models.TextField(blank=True, default="")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean"),
                            ("email", "Email"),
                            ("url", "URL"),
                            ("date", "Date"),
                            ("datetime", "Datetime"),
                            ("choice", "Choice"),
                            ("multichoice", "Multi-choice"),
                            ("file", "File"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("choices", models.JSONField(blank=True, null=True)),
                ("use_min_length", models.BooleanField(default=False)),
                ("min_length", models.PositiveIntegerField(blank=True, null=True)),
                ("use_max_length", models.BooleanField(default=False)),
                ("max_length", models.PositiveIntegerField(blank=True, null=True)),
                ("use_min_value", models.BooleanField(default=False)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                ("use_max_value", models.BooleanField(default=False)),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                ("use_regex", models.BooleanField(default=False)),
                (
                    "regex_pattern",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "regex_message",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("regex_flags", models.PositiveIntegerField(default=0)),
                ("use_email_validator", models.BooleanField(default=False)),
                ("use_url_validator", models.BooleanField(default=False)),
                ("use_slug_validator", models.BooleanField(default=False)),
                ("use_unicode_slug_validator", models.BooleanField(default=False)),
                ("use_file_extension_validator", models.BooleanField(default=False)),
                ("allowed_extensions", models.JSONField(blank=True, null=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="ehr.form",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("form", "key")},
            },
        ),
    ]
