# Generated by Django 6.0 on 2025-12-22 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_alter_participant_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last updated.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name of the form.", max_length=255
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description shown to users filling out the form.",
                        null=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        editable=False,
                        help_text="Unique identifier used in URLs and APIs.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive forms cannot receive new responses.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last updated.",
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        help_text="Submitted form data as a JSON object keyed by FormField.key."
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        help_text="Form that was filled out.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ehr.form",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        help_text="Donor who submitted this response.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.participant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last updated.",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Unique key used in Response.result JSON.",
                        max_length=100,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Label displayed to the end user.", max_length=255
                    ),
                ),
                (
                    "help_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional guidance shown to the user when filling out this field.",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean"),
                            ("email", "Email"),
                            ("url", "URL"),
                            ("date", "Date"),
                            ("datetime", "Datetime"),
                            ("choice", "Choice"),
                            ("multichoice", "Multi-choice"),
                            ("file", "File"),
                        ],
                        default="text",
                        help_text="Type of data expected for this field.",
                        max_length=20,
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this field must be provided in a response.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Controls display order of fields within the form.",
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        help_text="Used for Choice and Multi-choice fields. ",
                        null=True,
                    ),
                ),
                (
                    "use_min_length",
                    models.BooleanField(
                        default=False, help_text="Enable minimum length validation."
                    ),
                ),
                (
                    "min_length",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum allowed length (used if min length validation is enabled).",
                        null=True,
                    ),
                ),
                (
                    "use_max_length",
                    models.BooleanField(
                        default=False, help_text="Enable maximum length validation."
                    ),
                ),
                (
                    "max_length",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum allowed length (used if max length validation is enabled).",
                        null=True,
                    ),
                ),
                (
                    "use_min_value",
                    models.BooleanField(
                        default=False,
                        help_text="Enable minimum numeric value validation.",
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="Minimum allowed numeric value.",
                        max_digits=24,
                        null=True,
                    ),
                ),
                (
                    "use_max_value",
                    models.BooleanField(
                        default=False,
                        help_text="Enable maximum numeric value validation.",
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="Maximum allowed numeric value.",
                        max_digits=24,
                        null=True,
                    ),
                ),
                (
                    "use_regex",
                    models.BooleanField(
                        default=False, help_text="Enable regular expression validation."
                    ),
                ),
                (
                    "regex_pattern",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Regular expression pattern to validate the input.",
                        max_length=500,
                    ),
                ),
                (
                    "regex_message",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional custom error message for regex validation.",
                        max_length=255,
                    ),
                ),
                (
                    "regex_flags",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Python 're' module flags as an integer (e.g. IGNORECASE).",
                    ),
                ),
                (
                    "use_email_validator",
                    models.BooleanField(
                        default=False, help_text="Validate value as an email address."
                    ),
                ),
                (
                    "use_url_validator",
                    models.BooleanField(
                        default=False, help_text="Validate value as a URL."
                    ),
                ),
                (
                    "use_file_extension_validator",
                    models.BooleanField(
                        default=False,
                        help_text="Restrict uploaded files to specific extensions.",
                    ),
                ),
                (
                    "allowed_extensions",
                    models.JSONField(
                        blank=True,
                        help_text="List of allowed file extensions (e.g. ['pdf', 'png']).",
                        null=True,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        help_text="Form this field belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="ehr.form",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("form", "key")},
            },
        ),
    ]
