# Generated by Django 6.0 on 2025-12-26 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ehr", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ehr_assignments",
                to="projects.participant",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="ehr.form",
            ),
        ),
        migrations.AddField(
            model_name="formfield",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="ehr.form",
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ehr.form"
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="projects.participant"
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                fields=("participant", "form"), name="uniq_assignment_participant_form"
            ),
        ),
        migrations.AddConstraint(
            model_name="formfield",
            constraint=models.UniqueConstraint(
                fields=("form", "key"), name="uniq_form_field_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="response",
            constraint=models.UniqueConstraint(
                fields=("participant", "form"), name="uniq_response_participant_form"
            ),
        ),
    ]
