# Generated by Django 6.0 on 2025-12-18 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biobank", "0003_alter_aliquot_preparation_method_and_more"),
        ("ehr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when this record was created.",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Optional description shown to users filling out the form.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Inactive forms cannot receive new responses."
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="name",
            field=models.CharField(
                help_text="Human-readable name of the form.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="slug",
            field=models.SlugField(
                help_text="Unique identifier used in URLs and APIs.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Timestamp when this record was last updated.",
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="allowed_extensions",
            field=models.JSONField(
                blank=True,
                help_text="List of allowed file extensions (e.g. ['pdf', 'png']).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="choices",
            field=models.JSONField(
                blank=True,
                help_text="Used for Choice and Multi-choice fields. Either a list of values: ['a', 'b'] or objects: [{'value': 'a', 'label': 'Option A'}].",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when this record was created.",
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("integer", "Integer"),
                    ("decimal", "Decimal"),
                    ("boolean", "Boolean"),
                    ("email", "Email"),
                    ("url", "URL"),
                    ("date", "Date"),
                    ("datetime", "Datetime"),
                    ("choice", "Choice"),
                    ("multichoice", "Multi-choice"),
                    ("file", "File"),
                ],
                default="text",
                help_text="Type of data expected for this field.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="form",
            field=models.ForeignKey(
                help_text="Form this field belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="ehr.form",
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="help_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Additional guidance shown to the user when filling out this field.",
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="key",
            field=models.SlugField(
                help_text="Unique key used in Response.result JSON.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="label",
            field=models.CharField(
                help_text="Label displayed to the end user.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="max_length",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum allowed length (used if max length validation is enabled).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="max_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Maximum allowed numeric value.",
                max_digits=24,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="min_length",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum allowed length (used if min length validation is enabled).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="min_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Minimum allowed numeric value.",
                max_digits=24,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Controls display order of fields within the form."
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="regex_flags",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Python 're' module flags as an integer (e.g. IGNORECASE).",
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="regex_message",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional custom error message for regex validation.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="regex_pattern",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Regular expression pattern to validate the input.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="required",
            field=models.BooleanField(
                default=False,
                help_text="Whether this field must be provided in a response.",
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Timestamp when this record was last updated.",
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="use_email_validator",
            field=models.BooleanField(
                default=False, help_text="Validate value as an email address."
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="use_file_extension_validator",
            field=models.BooleanField(
                default=False,
                help_text="Restrict uploaded files to specific extensions.",
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="use_max_length",
            field=models.BooleanField(
                default=False, help_text="Enable maximum length validation."
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="use_max_value",
            field=models.BooleanField(
                default=False, help_text="Enable maximum numeric value validation."
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="use_min_length",
            field=models.BooleanField(
                default=False, help_text="Enable minimum length validation."
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="use_min_value",
            field=models.BooleanField(
                default=False, help_text="Enable minimum numeric value validation."
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="use_regex",
            field=models.BooleanField(
                default=False, help_text="Enable regular expression validation."
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="use_slug_validator",
            field=models.BooleanField(
                default=False, help_text="Validate value as an ASCII slug."
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="use_unicode_slug_validator",
            field=models.BooleanField(
                default=False, help_text="Validate value as a Unicode slug."
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="use_url_validator",
            field=models.BooleanField(
                default=False, help_text="Validate value as a URL."
            ),
        ),
        migrations.AlterField(
            model_name="historicalform",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Timestamp when this record was created.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalform",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Optional description shown to users filling out the form.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalform",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Inactive forms cannot receive new responses."
            ),
        ),
        migrations.AlterField(
            model_name="historicalform",
            name="name",
            field=models.CharField(
                help_text="Human-readable name of the form.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="historicalform",
            name="slug",
            field=models.SlugField(
                help_text="Unique identifier used in URLs and APIs.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="historicalform",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Timestamp when this record was last updated.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="allowed_extensions",
            field=models.JSONField(
                blank=True,
                help_text="List of allowed file extensions (e.g. ['pdf', 'png']).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="choices",
            field=models.JSONField(
                blank=True,
                help_text="Used for Choice and Multi-choice fields. Either a list of values: ['a', 'b'] or objects: [{'value': 'a', 'label': 'Option A'}].",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Timestamp when this record was created.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("integer", "Integer"),
                    ("decimal", "Decimal"),
                    ("boolean", "Boolean"),
                    ("email", "Email"),
                    ("url", "URL"),
                    ("date", "Date"),
                    ("datetime", "Datetime"),
                    ("choice", "Choice"),
                    ("multichoice", "Multi-choice"),
                    ("file", "File"),
                ],
                default="text",
                help_text="Type of data expected for this field.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="form",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Form this field belongs to.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ehr.form",
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="help_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Additional guidance shown to the user when filling out this field.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="key",
            field=models.SlugField(
                help_text="Unique key used in Response.result JSON.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="label",
            field=models.CharField(
                help_text="Label displayed to the end user.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="max_length",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum allowed length (used if max length validation is enabled).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="max_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Maximum allowed numeric value.",
                max_digits=24,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="min_length",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum allowed length (used if min length validation is enabled).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="min_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Minimum allowed numeric value.",
                max_digits=24,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Controls display order of fields within the form."
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="regex_flags",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Python 're' module flags as an integer (e.g. IGNORECASE).",
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="regex_message",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional custom error message for regex validation.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="regex_pattern",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Regular expression pattern to validate the input.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="required",
            field=models.BooleanField(
                default=False,
                help_text="Whether this field must be provided in a response.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Timestamp when this record was last updated.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="use_email_validator",
            field=models.BooleanField(
                default=False, help_text="Validate value as an email address."
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="use_file_extension_validator",
            field=models.BooleanField(
                default=False,
                help_text="Restrict uploaded files to specific extensions.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="use_max_length",
            field=models.BooleanField(
                default=False, help_text="Enable maximum length validation."
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="use_max_value",
            field=models.BooleanField(
                default=False, help_text="Enable maximum numeric value validation."
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="use_min_length",
            field=models.BooleanField(
                default=False, help_text="Enable minimum length validation."
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="use_min_value",
            field=models.BooleanField(
                default=False, help_text="Enable minimum numeric value validation."
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="use_regex",
            field=models.BooleanField(
                default=False, help_text="Enable regular expression validation."
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="use_slug_validator",
            field=models.BooleanField(
                default=False, help_text="Validate value as an ASCII slug."
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="use_unicode_slug_validator",
            field=models.BooleanField(
                default=False, help_text="Validate value as a Unicode slug."
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="use_url_validator",
            field=models.BooleanField(
                default=False, help_text="Validate value as a URL."
            ),
        ),
        migrations.AlterField(
            model_name="historicalresponse",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Timestamp when this record was created.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresponse",
            name="donor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Donor who submitted this response.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="biobank.donor",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresponse",
            name="form",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Form that was filled out.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ehr.form",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresponse",
            name="result",
            field=models.JSONField(
                help_text="Submitted form data as a JSON object keyed by FormField.key."
            ),
        ),
        migrations.AlterField(
            model_name="historicalresponse",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Timestamp when this record was last updated.",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when this record was created.",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="donor",
            field=models.ForeignKey(
                help_text="Donor who submitted this response.",
                on_delete=django.db.models.deletion.PROTECT,
                to="biobank.donor",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="form",
            field=models.ForeignKey(
                help_text="Form that was filled out.",
                on_delete=django.db.models.deletion.PROTECT,
                to="ehr.form",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="result",
            field=models.JSONField(
                help_text="Submitted form data as a JSON object keyed by FormField.key."
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Timestamp when this record was last updated.",
            ),
        ),
    ]
