# Generated by Django 6.0 on 2026-01-06 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ehr", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="formfield",
            name="uniq_form_field_order",
        ),
    ]
