# Generated by Django 5.2.7 on 2025-10-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehrrecord',
            name='data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
