# Generated by Django 6.0 on 2026-01-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ehr", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formfield",
            options={},
        ),
        migrations.AddConstraint(
            model_name="formfield",
            constraint=models.UniqueConstraint(
                fields=("form", "order"), name="uniq_form_field_order"
            ),
        ),
    ]
