# Generated by Django 6.0 on 2025-12-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ehr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description shown to users filling out the form.",
                null=True,
            ),
        ),
    ]
