# Generated by Django 6.0 on 2026-01-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ehr", "0002_remove_formfield_uniq_form_field_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="historicalassignment",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassignment",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalform",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalform",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresponse",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Object creation timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresponse",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Last object update timestamp.",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Object creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Last object update timestamp."
            ),
        ),
    ]
