# Generated by Django 6.0 on 2026-01-01 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ehr", "0002_alter_formfield_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formfield",
            options={"ordering": ("order",)},
        ),
    ]
