# Generated by Django 6.0 on 2025-12-22 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ehr", "0002_alter_form_description"),
        ("projects", "0002_alter_participant_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formfield",
            name="allowed_extensions",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="max_length",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="max_value",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="min_length",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="min_value",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="regex_flags",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="regex_message",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="regex_pattern",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="use_email_validator",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="use_file_extension_validator",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="use_max_length",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="use_max_value",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="use_min_length",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="use_min_value",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="use_regex",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="use_url_validator",
        ),
        migrations.AlterField(
            model_name="form",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="form",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="form",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="form",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="form",
            name="slug",
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="form",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="choices",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("integer", "Integer"),
                    ("decimal", "Decimal"),
                    ("boolean", "Boolean"),
                    ("date", "Date"),
                    ("datetime", "Datetime"),
                    ("choice", "Choice"),
                    ("multichoice", "Multi-choice"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="ehr.form",
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="help_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="key",
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="label",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="required",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="response",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="response",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ehr.form"
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="projects.participant"
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="result",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="response",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
