# Generated by Django 6.0 on 2026-01-08 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ehr", "0003_alter_assignment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="form",
            options={"ordering": ("created_at",)},
        ),
    ]
