# Generated by Django 6.0 on 2025-12-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ehr", "0003_remove_formfield_allowed_extensions_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="response",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="formfield",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="response",
            name="result",
            field=models.JSONField(default=dict),
        ),
        migrations.AddConstraint(
            model_name="formfield",
            constraint=models.UniqueConstraint(
                fields=("form", "key"), name="uniq_form_field_key"
            ),
        ),
    ]
