# Generated by Django 6.0 on 2025-12-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ehr", "0003_alter_historicalresponse_result_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="slug",
            field=models.SlugField(
                editable=False,
                help_text="Unique identifier used in URLs and APIs.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalform",
            name="slug",
            field=models.SlugField(
                editable=False,
                help_text="Unique identifier used in URLs and APIs.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicalresponse",
            name="result",
            field=models.JSONField(
                help_text="Submitted form data as a JSON object keyed by FormField.key."
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="result",
            field=models.JSONField(
                help_text="Submitted form data as a JSON object keyed by FormField.key."
            ),
        ),
    ]
