# Generated by Django 6.0 on 2025-12-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ehr", "0004_alter_form_slug_alter_historicalform_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="choices",
            field=models.JSONField(
                blank=True,
                help_text="Used for Choice and Multi-choice fields. ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalformfield",
            name="choices",
            field=models.JSONField(
                blank=True,
                help_text="Used for Choice and Multi-choice fields. ",
                null=True,
            ),
        ),
    ]
