# Generated by Django 6.0 on 2025-12-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ehr", "0005_assignment_remove_form_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="choices",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated values, e.g. a,b,c,d",
                max_length=1024,
                null=True,
            ),
        ),
    ]
