# Generated by Django 6.0 on 2025-12-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ehr", "0006_alter_formfield_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="token",
        ),
    ]
